### PR TITLE
Rework CSS for mobile snow conditions

### PR DESCRIPTION
**Pull request by brunobesson**
Was:
certif32

Now:
certif31

### CODE REVIEW

**Comment by brunobesson** [comment]
To be compared with display on larger screens using bootstrap striped table:
certif33

**Comment by stef74** [comment]
Low contrast ... many people complain about contrast

**Comment by brunobesson** [comment]
References #1446

**Comment by brunobesson** [comment]
>Low contrast 

What is low contrast? There is only black text (or dark grey) on white background.

**Pull request merged**
