### PR TITLE
Columns for firefox

### PR DESCRIPTION
**Pull request by ginold**
related to #690

### CODE REVIEW

**Comment by asaunier** [comment]
A minor comment else please merge when Travis is OK.

**Comment by ginold** [comment]
may i merge even with this error  ?

```
npm ERR! Failed at the c2corg_ui@0.0.1 prepublish script 'npm run snyk-protect'.
npm ERR! This is most likely a problem with the c2corg_ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run snyk-protect
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs c2corg_ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls c2corg_ui
npm ERR! There is likely additional logging output above.
```

**Comment by asaunier** [comment]
> may i merge even with this error ?

Is it really related to your changes?
Anyway it's better to figure what's wrong before merging. Do you have the same error when running the test in your instance?

**Comment by ginold** [comment]
the changes are just a few CSS lines so surely nothing to do. 

Tests with make check? no, i have no errors.

**Comment by tsauerwein** [comment]
I restarted the build on Travis, let's see.

**Pull request merged**
