### PR TITLE
Upload images sequentially

### PR DESCRIPTION
**Pull request by arnaud-morvan**
Relate #1340

### CODE REVIEW

**Comment by arnaud-morvan** [comment]
@asaunier @tsauerwein : this is ready for review.

**Comment by asaunier** [comment]
@arnaud-morvan That's awesome! :)
The code is OK for me.

I have tested the branch in my instance and it works really well (images uploaded 1 by 1 when drag-dropping for instance 10 images at the same time).

However I have often observed (almost every time) that at least an image (once 2) fails uploading because of a timeout error. Sometimes thrown only a few seconds after drag-dropping my set of images. It's not always the same image that fails when uploading the same 7 or so images.

**Comment by arnaud-morvan** [comment]
When using GPRS throttling, with big images (several Mo), I get normal timeout after 120s (the timeout of by images backend).

When we get an error, the corresponding image immediately disappear from the list, and the user cannot retry the upload, and do not knows which image have disappear.
IMHO we should keep and show informations about failed images, maybe add a retry button.

Apart from this, everything works fine for me. I do not reproduce your error. But if you get a timeout after a few second, this may come from your images backend, or it is not a real timeout.
https://github.com/c2corg/v6_ui/blob/3ed29c2fbfaaebf1c02659ae7771208fb27dd4e6/c2corg_ui/static/js/imageuploader.js#L259:L261

I suppose you use the default value for the images backend:
```
export image_backend_url = http://images.demov6.camptocamp.org
```
I will give it a try.

**Comment by asaunier** [comment]
> IMHO we should keep and show informations about failed images, maybe add a retry button.

+1
If the failed image card is removed, it's hard to figure out what image has not been uploaded.

> I suppose you use the default value for the images backend:

Indeed: https://github.com/c2corg/v6_ui/blob/master/config/alex#L7

If you think this is a problem not related with your changes, we can merge your PR, have the demo tested and if the problem persists, create a new issue about this.

**Comment by arnaud-morvan** [comment]
I've tested with the demov6 images backend that use async io http workers, and I get no timeout, everything seems ok with slow connection and big images.

**Comment by arnaud-morvan** [comment]
Now I show the retry/cancel button instead of removing the image from list.
User has to manually retry/cancel the image before he get the save button.

**Comment by asaunier** [comment]
> Now I show the retry/cancel button instead of removing the image from list.

I have just tested it: nice.
For me it's OK as is even though a bit of styling of the error message would be interesting to make it even more obvious (red font or red background?).

**Comment by asaunier** [comment]
Thanks for updating the error message styles :)
It looks really great now!

One more thing (sorry!): I have noticed the "Error while uploading the image" is not translated in my french interface whereas the string is available and translated in Transifex and in the i18n JSON file.

It seems using ``this.alerts_.gettext()`` is not enough to have the string actually translated:
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/alertservice.js#L35-L37

**Comment by arnaud-morvan** [comment]
Translation done using the translate attribute in the partial template.

**Comment by asaunier** [comment]
I have just tested it, it works fine now. Please merge when Travis is OK.

**Pull request merged**
