### PR TITLE
Translate an existing document into a new culture

### PR DESCRIPTION
**Pull request by asaunier**
Related to #10 
Requires https://github.com/c2corg/v6_api/pull/119

### CODE REVIEW

**Comment by tsauerwein** [comment]
:+1:

**Comment by asaunier** [comment]
Thanks @tsauerwein 
Your change in the API works fine: the editing form loads at least with the figures.
Saving the new culture still fails because locale are missing when pushing the form data to the API. More commits are to come...

**Comment by asaunier** [comment]
[ ] Fix "Cancel" link in editing form => cannot redirect to the current culture since it does not exist yet
[ ] Saving new culture fails

**Comment by asaunier** [comment]
PR is ready for reviewing.

**Comment by asaunier** [comment]
Mmmm Travis fails because of some unrelated error (I think):
```
touch .build/externs/angular-1.4-q_templated.js
mkdir -p .build/externs/
wget -O .build/externs/angular-1.4-http-promise_templated.js https://raw.githubusercontent.com/google/closure-compiler/master/contrib/externs/angular-1.4-http-promise_templated.js
--2016-01-07 19:16:19--  https://raw.githubusercontent.com/google/closure-compiler/master/contrib/externs/angular-1.4-http-promise_templated.js
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 23.235.46.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|23.235.46.133|:443... connected.
HTTP request sent, awaiting response... 502 Bad Gateway
2016-01-07 19:16:19 ERROR 502: Bad Gateway.
make: *** [.build/externs/angular-1.4-http-promise_templated.js] Error 8
```

**Comment by tsauerwein** [comment]
I restarted the build, let's see.

**Comment by asaunier** [comment]
> I restarted the build, let's see.

Thanks, it worked :)
I had restarted it too an hour ago but with no luck.

**Comment by gberaudo** [comment]
+1

**Comment by asaunier** [comment]
Thanks for reviewing. Merging.

**Pull request merged**
