### PR TITLE
Optimize waypoint update without geometry change

### PR DESCRIPTION
**Pull request by gberaudo**
If no geometry change are detected, remove the geometry from the PUT.
The API will detect the case and use the previous geometry.

### CODE REVIEW

**Comment by gberaudo** [comment]
Close: https://github.com/c2corg/v6_ui/issues/24

**Comment by gberaudo** [comment]
PR ready

**Comment by asaunier** [comment]
Makes sense to me.

**Comment by tsauerwein** [comment]
:+1:

**Comment by gberaudo** [comment]
Thank you for the review, will merge when https://github.com/c2corg/v6_api/pull/114 is merged.

**Comment by gberaudo** [comment]
Fixed an issue when creating a WP.

**Pull request merged**
