### PR TITLE
Fix missing translations

### PR DESCRIPTION
**Pull request by asaunier**
Related to https://github.com/c2corg/v6_ui/issues/627

### CODE REVIEW

**Comment by asaunier** [comment]
* [ ] For simple search / association tool i18n, see https://github.com/c2corg/v6_ui/issues/629
* [ ] OL3 (+ngeo?) i18n must be enabled as well (see how it's done in geomapfish)

**Comment by asaunier** [comment]
There's a dedicated issue for simple search / association tool i18n, see #629 => will need a dedicated PR.
Concerning OL3, no idea yet how to have the map items translations (but there are very few => not a big problem). Will make a separated PR if needed.

@ginold OK for merging the PR?

**Comment by ginold** [comment]
yep, looks good!

**Comment by asaunier** [comment]
Thanks!

**Pull request merged**
