### PR TITLE
Use fragment params for /auth page

### PR DESCRIPTION
**Pull request by tsauerwein**
To improve its *cachability*.

Closes https://github.com/c2corg/v6_ui/issues/585

### CODE REVIEW

**Comment by tsauerwein** [comment]
Must the SSO URL in Discourse also be updated? @gberaudo?

**Comment by asaunier** [comment]
No idea about the Discourse SSO URL but else LGTM.

**Comment by gberaudo** [comment]
@tsauerwein, yes I guess. But I don't know if Discourse supports this.

**Comment by tsauerwein** [comment]
> @tsauerwein, yes I guess. But I don't know if Discourse supports this.

I am afraid it [does not](https://github.com/discourse/discourse/blob/9018de39edd839bdb4e0a2b9f98aac9f76fbfe6f/lib/single_sign_on.rb#L82-L90). I will rework this.

**Comment by tsauerwein** [comment]
The URL will have to be updated in Discourse the next time the demo is updated:
https://github.com/c2corg/v6_forum/issues/43

**Comment by asaunier** [comment]
Are there still things to do with this PR?
If not, please merge.

**Pull request merged**
