### PR TITLE
Add emoji tag

### PR DESCRIPTION
**Pull request by cbeauchesne**
To test, add this markdown : 

    :smile: :paragliding: :webcam:

You should see emojis.

### CODE REVIEW

**Comment by cbeauchesne** [comment]
I've used the data model from emoji markdown extension. I guess that category is used for IHM helper, like fourm's one.

The unicode alt and unicode are special use case for extension that I havent implemented.

**Comment by brunobesson** [comment]
OK, thanks.

Could you please create an issue referencing this PR and label it with 'ready for demo'?

**Comment by cbeauchesne** [comment]
#1833 :)

**Comment by brunobesson** [comment]
My bad!

**Comment by cbeauchesne** [comment]
By the ay, is there a list of issue fixed by the today's release?

**Comment by brunobesson** [comment]
AFAIK, only 2 issues have been fixed, but many PRs did not have an associated issue. Aren't you subscribed to the dev mailing list? I sent an email about this today.

**Comment by cbeauchesne** [comment]
No, I did not receveid any mail. The release surprised me :)

**Comment by brunobesson** [comment]
I'll see if we can add you to the mailing list. I thought you already were.

**Comment by cbeauchesne** [comment]
I'd beleived too, I still had received mail from this ML...

**Comment by brunobesson** [comment]
Issue solved (I hope). Please check your emails.

**Pull request merged**
