### PR TITLE
Optimization of list

### PR DESCRIPTION
**Pull request by stef74**
I do a small PR to optimize layout of list outing. I prefer to not do a big to optimize all ... but by small enhance. 

before : 
capture d ecran 2017-11-19 a 21 57 45

after : 
capture d ecran 2017-11-19 a 21 56 30

### CODE REVIEW

**Comment by stef74** [comment]
after : 
capture d ecran 2017-11-20 a 13 17 43

before : 
capture d ecran 2017-11-20 a 13 25 32

**Comment by stef74** [comment]
ready for review

**Comment by stef74** [comment]
optim waypoint list on route with small screen. 
I have remove quality to take place and reduce icon size as suggets by @cbeauchesne 

after : 
capture d ecran 2017-11-20 a 20 38 27

before : 
capture d ecran 2017-11-20 a 20 37 07

**Comment by asaunier** [comment]
@stef74 No clue if the code changes are OK, perhaps @Courgetteandratatouille or @brunobesson could have a look? But at least the screen captures look really nice!

**Comment by stef74** [comment]
@c2corg/developers anybody for a review ?

**Pull request merged**
