### PR TITLE
Allow to associate books and articles when creating/editing a route

### PR DESCRIPTION
**Pull request by brunobesson**
Relates to #1298

### CODE REVIEW

**Comment by brunobesson** [comment]
I forgot to test that associated books and articles are effectively saved... and it's not working, sorry. Adding [WIP] prefix.

**Comment by brunobesson** [comment]
:confounded: 
I'm sorry to spam github. I think I'm getting tired, but before I tested creating a new route for a climbing site on the demo website, without it being set as main waypoint, and then got a 400 error when submitting, with the response `no association for the main waypoint : main_waypoint_id`.
But know, it isn't happening anymore (maybe it never was...). So I guess the problem is caused by those new associations.
If I try to submit a new route with additional book in associations, I get the bad request error.

Could someone try and tell me what's happening? Assuming the problem is caused by the new associations, is this then a bug or change to be made to the UI?

**Comment by brunobesson** [comment]
@tsauerwein maybe you can give me advice on whether the problem is API-related or I am missing something? Thx for your review.

**Comment by dkocich** [comment]
It is an API error here https://github.com/c2corg/v6_api/blob/master/c2corg_api/views/route.py#L66
You must set main WP like in the image for route 840251. I successfully added associations to mainWP/WP/routes/books/articles and saved my routes without error. It appears only when you do not have main WP selected.
image

**Comment by brunobesson** [comment]
Coming back to this PR, left appart for a few days. Thanks @dkocich for your feedback. As far as I understand, this PR looks OK for you. The problem with the main waypoint and the creation error is another issue (if it is one).

Thus, we could merge this PR?

**Comment by dkocich** [comment]
I am not sure if this error appears in logs - if yes, to prevent this it is maybe possible to hide save button when there is no Main WP set and show warning that it is required. Otherwise, it was ok for me and I let others decide about merging.

**Comment by asaunier** [comment]
> The problem with the main waypoint and the creation error is another issue

Indeed, I don't really see the connection between this PR about associated books/articles and main waypoints :)

@brunobesson  The PR looks good to me, except that a conflict should be resolved first.

**Pull request merged**
