### PR TITLE
Add support of anonymous xreports

### PR DESCRIPTION
**Pull request by asaunier**
Related to https://github.com/c2corg/v6_ui/issues/1507 (approach 2)
Requires https://github.com/c2corg/v6_common/pull/58
API part: https://github.com/c2corg/v6_api/pull/674

### CODE REVIEW

**Comment by asaunier** [comment]
This PR is ready to be reviewed.

What it does:
* add an ``anonymous`` attribute right above the associated users section in the xreport editing form (only when creating a report - existing reports cannot be made anonymous)
capture du 2017-07-05 12-44-26

* if checked, the associated users section is hidden (shown again if unchecked)
capture du 2017-07-05 12-44-38

* when submitting the form, if ``anonymous=true``, the associated users list is reset
* the API side assigns the report to some special account (which means the report can no longer be edited by the original author, only by moderators or by the special account owners)
capture du 2017-07-05 12-43-36
capture du 2017-07-05 12-44-01

**Comment by desnoes** [comment]
Nice !
@mgerbaux: which account should be associated as the author of the report ? We should have a special account for the SERAC DB moderators ?

**Comment by mgerbaux** [comment]
> which account should be associated as the author of the report ?

https://www.camptocamp.org/profiles/271737/fr

**Comment by asaunier** [comment]
@mgerbaux Thanks!
I have added this setting to the ``docker-compose.yml`` file of the demo and prod, to have them use the "Base accidents" account instead of the default "Camptocamp Association" account.

**Pull request merged**
