### PR TITLE
Homedesign

### PR DESCRIPTION
**Pull request by Courgetteandratatouille**
I guess it's ready for a test and maybe we can improve the performance of the column controller.

### CODE REVIEW

**Comment by asaunier** [comment]
Thanks @Courgetteandratatouille I'll try to give your feedbacks this WE.

**Comment by stef74** [comment]
@asaunier how to checkout it on my instance

**Comment by asaunier** [comment]
@stef74 It would have been easier if @Courgetteandratatouille had pushed his branch on the main repo instead of in his forked repo. Anyway it will be required to do so if we want to build a docker image and test it on the demo.

In the mean time you can for instance add @Courgetteandratatouille's repo in your remote:
* list of current remotes (repositories you can pull from/push to):
```
~/v6_ui$ git remote -v
origin	git@github.com:c2corg/v6_ui.git (fetch)
origin	git@github.com:c2corg/v6_ui.git (push)
```
* add a new remote:
```
~/v6_ui$ git remote add Courgetteandratatouille git@github.com:Courgetteandratatouille/v6_ui.git
~/v6_ui$ git remote -v
Courgetteandratatouille	git@github.com:Courgetteandratatouille/v6_ui.git (fetch)
Courgetteandratatouille	git@github.com:Courgetteandratatouille/v6_ui.git (push)
origin	git@github.com:c2corg/v6_ui.git (fetch)
origin	git@github.com:c2corg/v6_ui.git (push)
```
* get help:
```
~/v6_ui$ git remote --help
```
* get branches from the new remote:
```
~/v6_ui$ git fetch Courgetteandratatouille
remote: Counting objects: 42, done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 42 (delta 26), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (42/42), done.
From github.com:Courgetteandratatouille/v6_ui
 * [new branch]      homedesign -> Courgetteandratatouille/homedesign
   76c1528..08e041b  master     -> Courgetteandratatouille/master
```
* switch to a branch from this remote:
```
~/v6_ui$ git checkout Courgetteandratatouille/homedesign
```

**Comment by stef74** [comment]
stef@stef-VirtualBox:~/v6_ui$ git remote -v
Courgetteandratatouille	git@github.com:Courgetteandratatouille/v6_ui.git (fetch)
Courgetteandratatouille	git@github.com:Courgetteandratatouille/v6_ui.git (push)
origin	https://github.com/c2corg/v6_ui.git (fetch)
origin	https://github.com/c2corg/v6_ui.git (push)
stef@stef-VirtualBox:~/v6_ui$ git fetch Courgetteandratatouille
Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by Courgetteandratatouille** [comment]
@stef74 

I push the branch on the main depo in few hour :)

**Comment by stef74** [comment]
Ok found I need to use https:// instead git@github syntax.

**Comment by asaunier** [comment]
> Ok found I need to use https:// instead git@github syntax.

Probably because you are not using an SSH key to authenticate (you have to type your password every time you interact with the github repo, right? With an SSH key you don't). You could avoid this by having an SSH key and setting the public key to your github account https://github.com/settings/keys

**Pull request closed without merging**
