### PR TITLE
Climbing site: fields 'routes_quantity' and 'best_periods' are moived to the General section

### PR DESCRIPTION
**Pull request by desnoes**
Solution to #706

### CODE REVIEW

**Comment by asaunier** [comment]
> you built a branch out of contextual-help branch. instead, you should create a branch from master

@brunobesson good catch!
@desnoes It's important indeed to always create a new branch when making a new PR (your former "contextual-help" branch has been merged and could now be deleted). The new branch must be based on the very last version of the "master" branch.

**Comment by desnoes** [comment]
@asaunier @brunobesson : sorry, i did not realize. I will do it the right way this evening.

**Comment by asaunier** [comment]
@desnoes No big deal, thanks for the PR anyway :)
I agree information organisation in the document pages is really not optimal, there are plenty of other changes that we could do. See also issue https://github.com/c2corg/v6_ui/issues/1196

**Comment by brunobesson** [comment]
Replaced by #1740

**Pull request closed without merging**
