### PR TITLE
Fix response status check

### PR DESCRIPTION
**Pull request by asaunier**

### CODE REVIEW

**Comment by tsauerwein** [comment]
Looks good.

**Comment by asaunier** [comment]
Travis still fails...
Where do those ``Bad response: 500 Internal Server Error (not 404)`` come from in Travis reports?
I have no such errors when running the tests in my instance.

**Comment by asaunier** [comment]
@tsauerwein Do you think we still need this PR after the changes you have made to fix Travis tests?

**Comment by tsauerwein** [comment]
It is still needed, because otherwise it will fail when the API server does not respond or responds with an error.

**Comment by gberaudo** [comment]
+1 for merging.

**Pull request merged**
