### PR TITLE
fix paragliding_rating handling

### PR DESCRIPTION
**Pull request by ginold**
related to #937

### CODE REVIEW

**Comment by asaunier** [comment]
Could it be a problem with the API instead?
Shouldn't the API consider those values as strings instead of integers (even though it would be strings actually containing integers)?

**Comment by tsauerwein** [comment]
The paragliding ratings, like all other ratings, are enums. That why it has to be a string.

But why is the string converted to an integer? I thing the problem is here:
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/waypoint/edit.html#L485

Instead of `ng-options="rat as rat for rat in [1, 2, 3, 4, 5]"` is should rather be `ng-options="rat as rat for rat in ['1', '2', '3', '4', '5']"`. Or you could generate the options like for other enums.

**Comment by asaunier** [comment]
> Or you could generate the options like for other enums.

Definitely! It's not an option to hard code the values. They must always be retrieved from https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py

**Comment by ginold** [comment]
oh sorry, I didn't notice that those were not loaded from attributes.py. It has to be some old code :P

**Comment by ginold** [comment]
updated with ${paragliding_ratings}, works fine.

**Pull request merged**
