### PR TITLE
Useless details icon width on mobile

### PR DESCRIPTION
**Pull request by brunobesson**
I don't know why this rule exists. Whether when viewing a document or previewing an edit, it produces useless space between icon and title. Simply removing it is IMHO the best options

### CODE REVIEW

**Comment by asaunier** [comment]
I'm not sure to understand what the problem is. Perhaps you could provide a screenshot?

**Comment by gottferdom** [comment]
Before:
before
After:
after

This is difficult to explain the whole difference with only 2 screenshots. Still, the idea is to occupy more space on mobile.

**Comment by gottferdom** [comment]
I have also corrected the title max-width property on mobile.

**Comment by asaunier** [comment]
I would prefer @ginold reviews this PR since he's the specialist. But from my perspective (based upon the screenshots) your change makes sense, thanks.

**Comment by asaunier** [comment]
Tested in my instance, titles are indeed more efficiently placed. I have noticed no side effects.

**Pull request merged**
