### PR TITLE
Resize too big images before uploading them

### PR DESCRIPTION
**Pull request by asaunier**
Related to https://github.com/c2corg/v6_ui/issues/1046

In v5, client-side resizing is managed at https://github.com/c2corg/camptocamp.org/blob/72e777075f2e6260b1d2ef563ab0f90c383038ba/web/static/js/plupload.wrapper.js#L135-L144

* png and jpg images <2M will get resized only if they exceed c2c limits (8192x2048)
* images >2M will be resized to max 4096x1024
* svg and gifs won't be resized anyway

I have not fully succeeded in completing such a complicated pattern but the current PR at least adds the support of a simpler condition that might be already quite enough (at least as a first version?). Perhaps the resized dimensions should be confirmed. @lbesson @fbunoz @mgerbaux what do you think? See a962e23

It seems possible to pass as ``ngf-resize`` a function "returning a promise which resolves into the options" (see https://github.com/danialfarid/ng-file-upload#file-select-and-drop) that could probably be used to switch among resized dimensions depending on the file size but I have not figured out how to write such a promise function. Here is a piece of code that could be used as base:
```
/**
 * @param {Object} file
 * @return {Object}
 * @export
 */
app.ImageUploaderController.prototype.resizeOptions = function(file) {
  if (file.size > app.ImageUploaderController.MAX_IMAGE_SIZE) {
    return {'width': 4096, 'height': 1024, 'quality': 1.0};
  } else {
    return {'width': 8192, 'height': 2048, 'quality': 1.0};
  }
};
```
See also https://github.com/danialfarid/ng-file-upload/blob/052ea1942dfbe5cb9cb14b2caeb35fec15c3040d/src/model.js#L82-L99

### CODE REVIEW

**Comment by lbesson** [comment]
I don't know exactly how resizing works in v6 (and currently don't have time to look at it), but in v5, this is done using canvas. A few remarks:
* "c2c limits" where already there before I updated the upload code. This is some protection against odd formats, but it could probably be dropped (I mainly set it to prevent the image to be rejected by symfony, without questioning the "c2c limits")
* 4096x1024 was used as a compromise between quality and file size. (The goal is not to resize an image to something close to 2M, but to have a good looking image) Most of the time, the image was "good enough", but using canvas for resizing had some edge cases where these limits produced an image >2M, also it is too small for exotic formats like panoramas

Client-size resizing via canvas is quite quick, so we could make a better algorithm that would do several tries to find the best compromise depending on each image. But of course, doing something simple in the beginning (and maybe keep it simple afterwards) should be ok.

**Comment by asaunier** [comment]
Thanks @lbesson for the explanations.

I have the feeling that we should have a simpler config (at least first). I also think it is a bit a pity to resize images higher than 1024px.
Server side, the resizing is currently set to a max height of 1500px for BI images:
https://github.com/c2corg/v6_images/blob/master/c2corg_images/__init__.py#L7
In addition, since more and more devices have vertical display (eg. tablets), it's not that relevant to make a big distinction between width and height, except perhaps for panoramas. 

That's why I have set the check (and resizing params) to w=4096 and h=2048.
See https://github.com/c2corg/v6_ui/pull/1113/commits/a962e237a77beae05d5c21ff697420b70c56d34d

Does that make sense?
No idea if with such a config we would prevent downloading 2MB+ images?!

**Comment by lbesson** [comment]
maybe it would be easy to detect the orientation of the image by simply looking at the longest side.

Anyway, the 2MB restriction was only because one the server side, php was configured (well, it's default value) to refuse files larger that 2MB. And no resizing was performed by the server (aka file >2MB => error, files <2MB but bigger than c2c limits => error -- both errors being very frustrating for the user).

You seem to have resizing both on client and server side ?

One underlying question is whether it has sense to have quite big images (say >2MB) hosted on c2c :)

**Comment by tsauerwein** [comment]
> It seems possible to pass as ngf-resize a function "returning a promise which resolves into the options" (see https://github.com/danialfarid/ng-file-upload#file-select-and-drop) that could probably be used to switch among resized dimensions depending on the file size but I have not figured out how to write such a promise function.

The problem is that this function gets a list of files, but you only can return a single resize-parameter object, which is used for all files.

**Comment by asaunier** [comment]
> You seem to have resizing both on client and server side ?

The original is not resized server side. It's hosted as is.
Resized versions (BI, MI, SI) are indeed created, as in v5 actually.

Client side resizing is not enable yet, at least until this PR is merged :P 

> One underlying question is whether it has sense to have quite big images (say >2MB) hosted on c2c :)

I guess not because it would take some extra disc space.
On the other hand, perhaps in the future screens will be huge with big resolution and regenerating the BI images to bigger formats would be interesting.

I would say the main interest of client-side resizing is too reduce the upload-time and avoid the timeout problems we have encountered.

**Comment by asaunier** [comment]
@tsauerwein Thanks for the review.

As discussed together it's probably safer to wait that the prod is gone live before merging the PR (and make real-size testing in the demo).

**Pull request merged**
