### PR TITLE
Integrate the angular externs into the source

### PR DESCRIPTION
**Pull request by gberaudo**
Simplify extern management by having them in the source.
These are from closure-compiler version 04bdb72.

### CODE REVIEW

**Comment by asaunier** [comment]
Looks good to me, thanks!

**Comment by gberaudo** [comment]
Updated after discussion with @tsauerwein. There is now a dedicated README.md file explaining what are externs and how extern updates should be performed.

**Comment by tsauerwein** [comment]
Thanks for adding the readme. Please merge.

**Comment by gberaudo** [comment]
Thanks for the review.
@ginold, you should now rebase your PRs.

**Pull request merged**
