### PR TITLE
Don't delete the last associated route to outing + deleting only for appropriate user

### PR DESCRIPTION
**Pull request by ginold**
related to #694

but i'm not 100% sure it works as there have been issues with `userCtrl.hasEditRights`

### CODE REVIEW

**Comment by ginold** [comment]
@asaunier the PR seems to work now - I can delete the routes only from my own outing but not the last remaining one.

**Comment by asaunier** [comment]
If the PR is ready for reviewing, please update the title (and label the PR as ready?).

**Comment by ginold** [comment]
As you have moderator rights, you should check if you can delete a route from and edit any outing.

**Comment by asaunier** [comment]
> As you have moderator rights, you should check if you can delete a route from and edit any outing.

You can change your own permissions by setting the ``moderator`` attribute to ``True`` in your ``users.user`` table :P

**Comment by ginold** [comment]
it works as expected for moderators. May i merge?

**Comment by asaunier** [comment]
Please do, thanks!

**Pull request merged**
