### PR TITLE
show remove end date btn on mobile

### PR DESCRIPTION
**Pull request by ginold**
related to #1071

### CODE REVIEW

**Comment by asaunier** [comment]
For me this PR looks good but I have not tested it yet and am not sure to understand the related issue https://github.com/c2corg/v6_ui/issues/1071

@brunobesson since you have created the related issue and made several PR about styling in mobiles, perhaps you could review this PR and tell us if it's OK to merge it? Thanks!

**Comment by brunobesson** [comment]
@asaunier yes I can do that (next year though).
I created the issue which was merely a question to ensure it was the desired behavior, but I have no string feeling about the best choice.

**Comment by stef74** [comment]
@asaunier this PR can be merged ?

**Comment by asaunier** [comment]
@stef74 I was actually testing it. I think it is OK and will merge it.

**Comment by brunobesson** [comment]
Looks like I couldn't review it in time, sorry :confused:

**Comment by asaunier** [comment]
@brunobesson no problem :) Feel free to test this fix when the demo is updated.

**Pull request merged**
