### PR TITLE
Article categories in the edit form, fix of issue 803

### PR DESCRIPTION
**Pull request by dkocich**
Close https://github.com/c2corg/v6_ui/issues/803

Now I can view an article, edit and save it correctly.

1
image

2
image

3
image

### CODE REVIEW

**Comment by dkocich** [comment]
I did not do anything with languages. When I switch to FR it looks ok (but style can be maybe better later in case of many categories)

image

**Comment by asaunier** [comment]
I meant "in the editing form". That's because yesterday I have spent time fixing some fields that were not correctly translated in other editing forms and I wanted to make sure it was already OK for articles :P See https://github.com/c2corg/v6_ui/pull/806

**Comment by asaunier** [comment]
If the translations are OK in the editing form, feel free to merge, thank you very much :+1:

**Comment by dkocich** [comment]
FR, SPA, DE are ok... IT, BA, CA, EU are missing.

image

**Pull request merged**
