### PR TITLE
Show associated xreports on outings

### PR DESCRIPTION
**Pull request by dkocich**
Show associated xreports on outing's pages

Close https://github.com/c2corg/v6_ui/issues/1172

### CODE REVIEW

**Comment by brunobesson** [comment]
This bug was easy to fix! :+1:

**Comment by ginold** [comment]
I didn't see this one! but i'm having a more or less big PR coming  (#1227) where I also added xreports to outings, routes and wps. I think this PR can be deleted. 
BTW a review of mine would be great, if you have time!

**Comment by asaunier** [comment]
@dkocich Is this PR still needed?
Issue #1172 has been closed by https://github.com/c2corg/v6_ui/pull/1227

Could you close the PR if no longer needed? Thanks

**Comment by dkocich** [comment]
I think there was a problem with document type while adding, editing associations somewhere. I closed this one now and I will reopen if it will appear again.

**Pull request closed without merging**
