### PR TITLE
Only markdwon

### PR DESCRIPTION
**Pull request by cbeauchesne**
Final commit for https://github.com/c2corg/v6_ui/issues/1660

### CODE REVIEW

**Comment by cbeauchesne** [comment]
Note this PR must be widely tested on demo server :)

**Comment by asaunier** [comment]
```
1.91s$ make -f config/travis check
.build/venv/bin/flake8 c2corg_ui
c2corg_ui/format/__init__.py:20:80: E501 line too long (81 > 79 characters)
c2corg_ui/format/__init__.py:21:80: E501 line too long (83 > 79 characters)
c2corg_ui/format/__init__.py:24:80: E501 line too long (86 > 79 characters)
c2corg_ui/format/__init__.py:25:80: E501 line too long (88 > 79 characters)
c2corg_ui/format/__init__.py:29:80: E501 line too long (98 > 79 characters)
c2corg_ui/format/__init__.py:30:80: E501 line too long (102 > 79 characters)
c2corg_ui/format/__init__.py:33:80: E501 line too long (104 > 79 characters)
c2corg_ui/format/__init__.py:92:80: E501 line too long (108 > 79 characters)
c2corg_ui/format/img.py:71:80: E501 line too long (111 > 79 characters)
c2corg_ui/format/video.py:24:80: E501 line too long (101 > 79 characters)
c2corg_ui/format/video.py:39:80: E501 line too long (111 > 79 characters)
make: *** [flake8] Error 1
```
:P

**Comment by cbeauchesne** [comment]
My editor was configured for 120 chars ^^

**Comment by cbeauchesne** [comment]
well ell, to be frank, I do not know what to do for merging. Merging into master is not what we need, but merging my branch into c2corg.v6_ui for testing. How can i do that?

**Comment by asaunier** [comment]
> but merging my branch into c2corg.v6_ui for testing. How can i do that?

You have to push your branch to the main repo (not in your fork), in order to have the docker image generated and made available at https://hub.docker.com/r/c2corg/v6_ui/tags/ Then we could update the demo with this image.

**Pull request closed without merging**
