### PR TITLE
Map btns alignment

### LINKED ISSUE #801: Style for map tools looks broken (FF)
c2corg-map-tools

It looks better on Chrome.

### PR DESCRIPTION
**Pull request by ginold**
fixes #801

and a new suggestion: i put the map-filter-switch on the bottom and there is always space for all the map's buttons.

screenshot from 2016-10-31 18-52-54

### CODE REVIEW

**Comment by asaunier** [comment]
Interesting!
A small drawback of this change is that the "filter on map extent" option is a bit less visible.
Please also note that the layer names in the base layer selector are longer when actually translated (test when browsing in French for instance).

**Comment by ginold** [comment]
ah those french translations... :P you are right, in french for example it's too long and on smaller screens it slightly overflows the borders, but it's already surely better. I think "limiter la recherche à la carte visible" is a bit too literal. Maybe simply "filter par carte" or something? 

Or i can simply move this filter just above the base-layer selector and the turn is played (le tour est joué).

**Comment by asaunier** [comment]
>  in french for example it's too long

What about making the text wrap on 2 lines?
I agree the translations is a bit too long but it's important that it's clear enough, else users won't understand what it's used for.

In airbnb it's "Rechercher quand je déplace la carte"
https://www.airbnb.fr/s/Lausanne--Suisse?page=1&s_tag=kfMa3CwJ&allow_override%5B%5D=
@shortoland What do you think?

**Comment by ginold** [comment]
wrapping on 2 lines:
screenshot from 2016-11-02 11-19-53

moved up:
screenshot from 2016-11-02 11-21-43


which one do you like more?

**Comment by asaunier** [comment]
I don't have a strong opinion.
The first option is more "discrete" (but is it really what we want?), because more integrated.

My concern is that this tool is not obvious enough.

Would it be possible/complicated to leave it in the top right corner (with a max-width and a text wrap if needed) and if the map is too narrow (conflict with the search input), to make it jump on the next line?

**Comment by ginold** [comment]
will try!

**Comment by ginold** [comment]
PR updated: filter switch on top - goes onto the next line when no space - and wraps even more if really little space.

**Comment by asaunier** [comment]
That's great!! Thanks a lot!
Please merge.

**Pull request merged**
