### PR TITLE
Jwaddle filter sliders

### PR DESCRIPTION
**Pull request by julsbreakdown**
#1781

### CODE REVIEW

**Comment by asaunier** [comment]
Instead of pushing a new commit (cherry-pick?), it's easier/faster/clearer to make a rebase:
```
git fetch
git rebase origin/master
```

**Comment by julsbreakdown** [comment]
His fix was on the api side

**Comment by asaunier** [comment]
Oops, then OK :+1: 
Please merge

**Comment by julsbreakdown** [comment]
Thanks anyway for the info =)

**Pull request merged**
