### PR TITLE
fix #1640 : Unit test structure for markdown/bbcode parser

### LINKED ISSUE #1640: Markdown unit test
@asaunier I create a separate issue for that, if we agree on the content, I will make a PR.

I propose this : A folder named tests/ that contains files with two behaviors :

* json files with a list of {id, markdown, expected} -> they will contain short md codes. Having several file will help to organize test case
* Couple of file .md and .html (for instance MyTest.md comes with MyTest.html). .md file contains markdown code, .html file contains expected result.

The code will scan entire folder, and will run test on all files. 

Your opinion?

### PR DESCRIPTION
**Pull request by cbeauchesne**
I've keept actual test, and put them in new model

### CODE REVIEW

**Comment by stef74** [comment]
Plase use an explicit title

**Comment by asaunier** [comment]
Thanks @cbeauchesne I'll test your PR at home tonight or at lunch time.

Indeed it is easier for reviewers to have an explicit title for the PR, ditto for the commit message: when looking at the commits list https://github.com/c2corg/v6_ui/commits/master it's not very easy to understand what the commit does when only entitled ``fix #1640``.

On the other hand it is welcome to make a link to the issue in the PR comment. If you use fix/fixes/close/closes + ``issue id`` the issue is automatically closed when the PR is merged. Generally we prefer not to autoclose the issue (except if it is not a really visible change) and tag the issue "ready for demo" instead => this way we know what are the changes when creating a new release https://github.com/c2corg/v6_ui/releases

**Comment by cbeauchesne** [comment]
@asaunier, sure for explicit titles. I uselly work alone on github's repos, and tends to have bad habits to not comment my commits, and auto fix issues with comments. I'll will make on effort on that point in the future :smile:

**Comment by asaunier** [comment]
Perhaps another tip: it's better to create a new branch instead of using the master branch of your fork. This may be useful for instance if you plan to do other pull requests at the same time.

I don't know if it can help but I have recently created a short cookbook about some git commands I find useful: https://github.com/c2corg/v6_ui/wiki/Git-Cookbook

**Comment by cbeauchesne** [comment]
@asaunier sure, yet another bad habit to fight :smile: 

Thank you very much for your *git for dummies*, it will help!

**Pull request merged**
