### PR TITLE
Design of multi-pitch description (L#)

### PR DESCRIPTION
**Pull request by fbunoz**
Improve design of L# table : 

- desktop : remove column min-width
- mobile : use flexbox instead table cell

design_longueur_mobile

### CODE REVIEW

**Comment by asaunier** [comment]
@fbunoz Thanks, I will test your changes at home and give you feedbacks.

Is there a reason for having 2 commits instead of 1? You can squash commits together, see https://github.com/c2corg/v6_ui/wiki/Git-Cookbook#managing-commits

When developing, you can amend the last commit (ie. add more changes to it), using
```
git add <updated file path>
git commit --amend
```

**Comment by fbunoz** [comment]
The squash can be done during the merge. There is a option : "squash and merge".

**Comment by asaunier** [comment]
I know, but it's always better for reviewers to have a clean and neat PR with the minimal number of commits!

**Comment by asaunier** [comment]
The result looks really cool in small screens!
But it seems to me the changes make some columns really too narrow (in my Chrome browser). See

capture d ecran 2017-09-28 a 22 41 40
capture d ecran 2017-09-28 a 22 47 53

@Courgetteandratatouille Do you think those changes in the .less files will conflict with yours about the new layout?

**Comment by fbunoz** [comment]
> it seems to me the changes make some columns really too narrow (in my Chrome browser).

I don't see that on Firefox.
I don't know how to fix this problem on chrome.
Is this probem exist also in prod ? And on V5 ?
See this route : https://www.camptocamp.org/routes/54443/fr/le-grand-manti-voie-de-la-rampe
The last lines have long ratings, but there is no word-wrapping on Firefox.

**Comment by asaunier** [comment]
> Is this probem exist also in prod ? And on V5 ?

V5: I don't know.
Prod: no problem. 

capture d ecran 2017-09-30 a 00 05 23

**Comment by fbunoz** [comment]
On prod you have also the problem : /A0 is on a new line. With firefox, all
the rating is on the same line.
In this case, it is better to wrap the long ratings, but if chrome cut also
a short rating (between 6 and a) to have only one letter per line, it isn't
good.

Le 30 sept. 2017 12:06 AM, "Alex Saunier" <notifications@github.com> a
écrit :

**Comment by asaunier** [comment]
@fbunoz Compare my screenshots: with your changes, the pitch length column is 1-character wide, which does not happen in prod. The current state of the prod is acceptable to me, not with your changes.

**Comment by fbunoz** [comment]
The current design in prod is not acceptable for me, because the columns
are too large, and it doesn't let enough place for the description column
when there are 5 columns (L1 6a 30m 3p blabla) + a picture at right, even
with a large screen.
I'll try another solution...

Le 30 sept. 2017 11:33 AM, "Alex Saunier" <notifications@github.com> a
écrit :

**Comment by fbunoz** [comment]
I add rules to force no word breaking. Maybe the default value for Chrome allows the word breaking.

**Comment by asaunier** [comment]
Please update your branch, in order to get rid of the errors reported by Travis (see the checks reports). See the instructions at https://github.com/c2corg/v6_ui/wiki/Git-Cookbook#updating-ones-branch-with-commits-pushed-to-branch-master-in-the-meantime

**Comment by fbunoz** [comment]
@asaunier : try the new design from Courgette : http://176.31.110.197:6553/routes/54443/fr/le-grand-manti-voie-de-la-rampe
It removes the min-width as in my PR.
I don't see the bad behavior on Chrome on Android.

**Comment by asaunier** [comment]
> http://176.31.110.197:6553/routes/54443/fr/le-grand-manti-voie-de-la-rampe
It set the min-width to 0 on mobile, but it keep the table layout.

It seems OK to me.

**Comment by asaunier** [comment]
@fbunoz @Courgetteandratatouille Is this PR still valid or has it been integrated in the redesign PR https://github.com/c2corg/v6_ui/pull/1783 ?

**Comment by Courgetteandratatouille** [comment]
i integrate there change on my branch, we can close this PR :)

**Comment by asaunier** [comment]
@fbunoz If OK for you, please close the PR and delete the associated branch (a button appears after closing the PR).

**Comment by fbunoz** [comment]
Integrated in #1783

**Pull request closed without merging**
