### PR TITLE
API consistency changes

### PR DESCRIPTION
**Pull request by asaunier**
Closes https://github.com/c2corg/v6_ui/issues/619

### CODE REVIEW

**Comment by asaunier** [comment]
This PR addresses all points mentioned at https://github.com/c2corg/v6_ui/issues/619

Commit fdb5ae7 might not be needed, it depends if there's a consistency issue in the API. See https://github.com/c2corg/v6_ui/issues/619#issuecomment-247307134

I have noticed 2 problems in the outing editing page:
* the user name is missing in the card of the current user (by default in the associated users). Most likely not related to this PR since the same behaviour is observed in the demo. I have created a new issue for this: https://github.com/c2corg/v6_ui/issues/623
* when using the route association tool in the outing editing form, the following error is returned many times after selecting a result. Then again when moving to the next step or when making a new search. Ditto with the user association tool. No error is shown in debug mode! No problem in the detail view page. No problem on the demo (yet?).
> deps.js:157 TypeError: Cannot read property 'length' of undefined
    at so.Z.ig (build.js:426)
    at fn (eval at compile (deps.js:272), <anonymous>:4:509)
    at m.$digest (deps.js:182)
    at m.$apply (deps.js:185)
    at HTMLInputElement.<anonymous> (build.js:353)
    at HTMLInputElement.dispatch (deps.js:5)
    at HTMLInputElement.r.handle (deps.js:5)
    at Object.trigger (deps.js:6)
    at HTMLInputElement.<anonymous> (deps.js:6)
    at Function.each (deps.js:4)

Don't know what we could do for the latter error...

**Comment by asaunier** [comment]
A quick review of this PR would be cool because in the meantime, several pages are broken since the changes in the API.

**Comment by tsauerwein** [comment]
> Don't know what we could do for the latter error...

In `build.json` you could add the option `"formatting": "pretty_print"` to get more context.

**Comment by asaunier** [comment]
> In build.json you could add the option "formatting": "pretty_print" to get more context.

Thanks for the tip. Well, even with that option I'm still a bit confused with this error.

**Comment by asaunier** [comment]
@ginold Is the PR OK for you? Do you see other places where the associated users ``id`` should be converted to ``document_id``?

**Comment by asaunier** [comment]
Merging because it's a pain in the neck to have all those API-changes-related errors when working on the UI.

**Pull request merged**
