### PR TITLE
Finishes on images modal dialog

### PR DESCRIPTION
**Pull request by arnaud-morvan**

### CODE REVIEW

**Comment by arnaud-morvan** [comment]
@ginold : can you review

**Comment by ginold** [comment]
I encounter an error when uploading multiple images: when dropping for example 3 images, only the last one will upload. Same when I want to abort uploading images one by one - there are some errors.

Uploading and cancelling one image at a time works fine.

**Comment by ginold** [comment]
and uploading one image, selecting the type and then uploading a second image, selecting the type and clicking on save also throws an error.

**Comment by arnaud-morvan** [comment]
Bug fixed, merging

**Pull request merged**
