### PR TITLE
Fix position of map recentering tools with Safari/iOS

### PR DESCRIPTION
**Pull request by asaunier**
Port of changes suggested by @dkocich at 5355ab671d2c0a84d12561700d7966aaab948ad1

Related to https://github.com/c2corg/v6_ui/issues/1137
Replace PR https://github.com/c2corg/v6_ui/pull/1506

Should be deployed on the demo to be tested on various devices and browsers.

### CODE REVIEW

**Comment by brunobesson** [comment]
@asaunier sorry I have no safari browser and cannot test your PR

**Comment by asaunier** [comment]
@desnoes What's the conclusion of the tests? Is it worth merging this PR or not? Does it provide any improvement with Safari and no side-effect with other browsers?

**Comment by desnoes** [comment]
@asaunier: it is not worth merging the PR. The problem remains with Safari and the modification hides the button on Chrome (Androïd).

**Comment by asaunier** [comment]
@desnoes OK thanks for the feedback. Then I close the PR.

**Pull request closed without merging**
