### PR TITLE
Define full-width homepage toolbar on mobile

### PR DESCRIPTION
**Pull request by brunobesson**
Before:
snapshot7

After:
snapshot8

### CODE REVIEW

**Comment by asaunier** [comment]
@brunobesson Perhaps my eyes have not fully recovered yet, but I don't really see the difference between your screenshots :P

**Comment by brunobesson** [comment]
That's because the contrast is week :wink: 
Magnify the left part.

**Comment by asaunier** [comment]
To be honest I still see everything on my screen a bit blurry. So I can't really tell :P

**Comment by brunobesson** [comment]
When playing with curves to accentuate the difference: snapshot12

**Comment by ginold** [comment]
:+1:  eye of the eagle!

**Pull request merged**
