### PR TITLE
configuration buttons mobile layout

### PR DESCRIPTION
**Pull request by brunobesson**
Move text to the right of the buttons

(note that I have tested it in the browser but cannot test it with compiled CSS, so I might have a bug, but it's easy to test)

### CODE REVIEW

**Comment by gottferdom** [comment]
Before
before

After
after

**Comment by asaunier** [comment]
@ginold a review for you :)

@gottferdom That looks nice to me indeed! Perhaps it's not very consistent with the positioning of the labels of the usual float buttons (placed under the icons). But anyway those feed buttons are rendered differently in bigger screens, so perhaps it's not a problem.

**Comment by gottferdom** [comment]
@asaunier yes, indeed, and I have opened another issue for this case. The difference being that the text is quite long (on two lines for both buttons), and there are only 2 buttons. So it make sense to me to do it this way.
The default case, with 4 buttons also has problems (see #989).
The 3 buttons when editing (preview, OK, cancel) do not have text.
Maybe I am missing other case.
So there is no consistent behaviour either :laughing:

**Comment by asaunier** [comment]
Looks good to me. I'm OK for merging. @ginold OK for you?

**Comment by ginold** [comment]
If it doesn't impact for the bad the other float-buttons (view page, editing page) in desktop/mobile mode and in other languages - then go ahead !

**Pull request merged**
