### PR TITLE
Hide geometry diff if there is... no diff!

### PR DESCRIPTION
**Pull request by brunobesson**
The problem remaining will be the case of an update GPX track: as this is not handled by the diff, no modification is shown
@asaunier do you think we should create an API issue for this?

### CODE REVIEW

**Comment by brunobesson** [comment]
Relates to #1874

**Comment by asaunier** [comment]
What's the use of the new file ``package-lock.json``?

> The problem remaining will be the case of an update GPX track: as this is not handled by the diff, no modification is shown
@asaunier do you think we should create an API issue for this?

Sorry, I don't understand the question?! If the geometry is changed I think the diff at least shows the different "central point" geom, doesn't it?

**Comment by brunobesson** [comment]
>What's the use of the new file package-lock.json?

Sorry, must have been appended when rebasing (didn't chek after). This file is added with recent npm versions, but we don't want it.

>If the geometry is changed I think the diff at least shows the different "central point" geom, doesn't it?

Yes, sure. My question would be what is shown if I edit the GPX track of a route : the diff does not show it, does it?

**Comment by asaunier** [comment]
I think the diff never show the full geometries, only the ``geom`` attribute (ie. a point geometry representing the line geometry at its barycenter or something like that).

**Pull request merged**
