### PR TITLE
Always regenerate template files

### PR DESCRIPTION
**Pull request by gberaudo**
This PR makes sure the files are generated and up-to-date.

### CODE REVIEW

**Comment by asaunier** [comment]
Could you give more details? Why do we need this? What was the problem?

**Comment by gberaudo** [comment]
- when you did make check from a fresh clone it would error since no test.ini was generated;
- when you did make -f config/alex install; then make -f config/main install it would use generated files for alex.

**Comment by gberaudo** [comment]
Added a fix a strange bug: when building on Travis, v6_api path was included in the template path.
Don't know why it worked previously.

**Comment by tsauerwein** [comment]
> Added a fix a strange bug: when building on Travis, v6_api path was included in the template path.
Don't know why it worked previously.

Before, the ui project was built, after that the api project was checked out and built. So, the moment the templates were generated for the ui project, the api project was not there yet. But now, when you start the tests for the ui, the template files are re-generated.

**Comment by gberaudo** [comment]
Thanks for the explanations @tsauerwein. It makes sense.

> The template files are re-generated when one of the config/* files has changed?
Do you mean the dependency is now useless and I should remove it?

**Comment by gberaudo** [comment]
Removed useless dependency on config files.

**Comment by tsauerwein** [comment]
I think that looks good!

**Comment by gberaudo** [comment]
Thanks for the review @tsauerwein and @asaunier. I will create a similar PR for the API.

**Pull request merged**
