### PR TITLE
not display author name in feed

### PR DESCRIPTION
**Pull request by stef74**

### CODE REVIEW

**Comment by asaunier** [comment]
Screenshot?

**Comment by stef74** [comment]
capture d ecran 2017-03-31 a 22 32 01

**Comment by asaunier** [comment]
It doesn't impact the advanced search lists and the associated outings lists?
Only the home/profile feeds?
If yes OK for me.

**Comment by stef74** [comment]
yes only for feed.

2017-04-01 19:16 GMT+02:00 Alex Saunier <notifications@github.com>:

**Pull request merged**
