### PR TITLE
Use fragment params for filters

### PR DESCRIPTION
**Pull request by tsauerwein**
Closes https://github.com/c2corg/v6_ui/issues/554

ngeo has to be updated after https://github.com/camptocamp/ngeo/pull/1686 is merged.

### CODE REVIEW

**Comment by asaunier** [comment]
> ngeo has to be updated after camptocamp/ngeo#1686 is merged.

See also this PR (and the open problems!) about upgrading ngeo and openlayers: https://github.com/c2corg/v6_ui/pull/529

**Comment by tsauerwein** [comment]
Ready to review

**Comment by asaunier** [comment]
LGTM

**Comment by tsauerwein** [comment]
Thanks for the review and help with this.

**Pull request merged**
