### PR TITLE
API uses a new output format for documents lists

### PR DESCRIPTION
**Pull request by asaunier**
Related to those changes in the API: https://github.com/c2corg/v6_api/pull/28 https://github.com/c2corg/v6_api/issues/49

### CODE REVIEW

**Comment by tsauerwein** [comment]
Your changes look ok, but the tests fail on Travis.

**Comment by asaunier** [comment]
Thanks for the review.
Yes, Travis fails. But the checks pass on my instance. Why such a difference?

**Comment by tsauerwein** [comment]
Is your API instance that you are using to run the tests up-to-date with master?

**Comment by asaunier** [comment]
Yes, it is.

By the way why do we have those ``AttributeError: 'dict' object has no attribute 'status'`` errors when the corresponding code has not changed. The only thing that has changed is the content of the response, isn't it?

**Comment by tsauerwein** [comment]
Yes, but the request to the API server fails. Just merge this PR so that you are not blocked, and we'll figure out later why the tests do not work on Travis.

**Comment by asaunier** [comment]
I have made sure my API was up-to-date (the tests should fail if it wasn't!).
Checks pass in my UI instance.

I have tried to restart the Travis tests but with no luck.

As you suggested, I try to merge the PR.

**Pull request merged**
