### PR TITLE
Convert WP coordinates before passing them to templates

### PR DESCRIPTION
**Pull request by asaunier**
The conversion is done in the view. I wonder if it should be done in the mako templates instead (since we  will also need the geometry for the map).

### CODE REVIEW

**Comment by tsauerwein** [comment]
> I wonder if it should be done in the mako templates instead (since we will also need the geometry for the map).

Especially since we will have to reproject again to get the coordinates in 'epsg:3857' for the map.

**Comment by asaunier** [comment]
New version: a "transform" function is passed to the template and may be applied on the geometry directly in the template.

Next step is to add tests about geometry reprojecting.

**Comment by asaunier** [comment]
> Next step is to add tests about geometry reprojecting.

Done with 6465fd9

Please review.

**Comment by tsauerwein** [comment]
Sorry, I think I misunderstood you. I thought you would want to do the reprojection in Javascript (which doesn't sound like a good idea in this case in hindsight ;).

I would have passed the geometry in the two different projections to the template. But feel free to leave it like this.

            'geometry': self._get_geometry(waypoint['geometry']['geom']),
            'geometry4326': self.transform_(...)

**Comment by asaunier** [comment]
> I would have passed the geometry in the two different projections to the template.

That's an option indeed. Do you think your approach makes much sense?
I thought that was the responsability of the template to adapt the data according to what it needs to do. We might have to reproject to additional coordinates system as well. For instance EPSG:21781 in Switzerland or even lon/lat in deg/min/sec.
See for instance http://www.camptocamp.org/summits/40507/fr/li-blanche

**Comment by tsauerwein** [comment]
If you see reprojection like for example formatting a number, I think it is ok to call the transformation from the template.

**Comment by asaunier** [comment]
I have pushed a new version of the tests, using assertAlmostEqual and testing the EPSG:21781 projection as well.

Since you seem OK with this PR, I will merge it soon if no last objection is raised.

**Comment by tsauerwein** [comment]
:+1:

**Pull request merged**
