### PR TITLE
Switch to Python 3.4

### PR DESCRIPTION
**Pull request by tsauerwein**
See https://github.com/c2corg/v6_api/pull/124

The only Python package that does not support Python 3 is closure-linter. Because the package is only needed to run the linter, I simply create a second virtualenv with Python 2.7 and install closure-linter in there. There are [no plans](https://github.com/google/closure-linter/issues/81#issuecomment-170260192) to add support for Python 3, so in the long run we have to find a replacement for closure-linter.

### CODE REVIEW

**Comment by tsauerwein** [comment]
> The only Python package that does not support Python 3 is closure-linter. Because the package is only needed to run the linter, I simply create a second virtualenv with Python 2.7 and install closure-linter in there. There are no plans to add support for Python 3, so in the long run we have to find a replacement for closure-linter.

Problem solved by replacing closure-linter (and JsHint) with ESLint. The same rules as for ol3 are used with some exceptions.

**Comment by tsauerwein** [comment]
Ok for merging this PR as well? Any opinions on ESLint?

**Comment by asaunier** [comment]
OK for me

**Comment by gberaudo** [comment]
+1 for switching to ESLint and basing our config on the one from OpenLayers.
The only drawback seems to be the spacing change before constructors.

**Comment by tsauerwein** [comment]
So Python 3 it is. :)

**Pull request merged**
