### PR TITLE
Upgrade some JS packages

### PR DESCRIPTION
**Pull request by asaunier**
I have noticed some recent upgrades in the packages of ngeo:
https://github.com/camptocamp/ngeo/blob/master/package.json

This PR does the same for c2corg. I have not upgraded ngeo and ol3. Don't know if I should.

### CODE REVIEW

**Comment by asaunier** [comment]
Any objections? :)

**Comment by tsauerwein** [comment]
No, thanks!

**Comment by ginold** [comment]
you must have been really bored...:P

**Comment by asaunier** [comment]
> No, thanks!

Thanks

> you must have been really bored

Indeed :P

**Pull request merged**
