### PR TITLE
Remove duplicated property in simple search externs

### PR DESCRIPTION
**Pull request by asaunier**
Fixes https://github.com/c2corg/v6_ui/issues/374

### CODE REVIEW

**Comment by asaunier** [comment]
Any objections?

**Comment by tsauerwein** [comment]
The simple search [returns](http://c2corgv6-api.demo-camptocamp.com/search?q=mon&pl=en) `type` so your change does not look correct?

**Comment by asaunier** [comment]
Perhaps, but as I said it doesn't seem to work with ``type``, only with ``documentType``!?

**Comment by ginold** [comment]
very very likely `documentType` has been created long time ago by me, when `type` wasn't returned yet and probably there are some functions that still use `documentType`.

**Pull request closed without merging**
