### PR TITLE
make remember me the default option

### PR DESCRIPTION
**Pull request by ginold**
set's "remember me" checkbox by default + some styling.

Fixes https://github.com/c2corg/v6_ui/issues/259

### CODE REVIEW

**Comment by gberaudo** [comment]
LGTM

**Comment by ginold** [comment]
LGBT

**Comment by asaunier** [comment]
It would have been easier to read/review to have splited the changes in 2 commits, 1 for the "remember me" default status, 1 for the styling.
Currently it is very hard to figure out where this change about "remember me" is done...

**Comment by ginold** [comment]
to be honest, the only line that would make "remember me" default is ` <input type="checkbox" name="remember" ng-model="login.remember" ng-checked="true">`, the rest is styling.

**Comment by asaunier** [comment]
> to be honest, the only line that would make "remember me" default is <input type="checkbox" name="remember" ng-model="login.remember" ng-checked="true">, the rest is styling.

Yep, that's why I think it should have been done a commit, the rest in a second "styling" one.
Looking a your PR, it's not obvious where the change "make remember me the default option" is done.

**Comment by gberaudo** [comment]
> LGBT

@ginold what do you mean?

**Comment by asaunier** [comment]
OK for the "remember me" change.

Concerning the styling changes, they look fine except that:
* it would make more sense to place the "no account yet?" button right next buttons "Login", "Forgot password?" (and not in some deported place to the right) => all options are at the same place, easy to see and use.
* why using a different text styling for "no account yet?" and "Forgot password?" compared to "Login"?
* the showing of the various forms ("login", "register", "reset password") is not consistent => depending on what buttons you clicked and in what order you see different combinations of forms. For instance if you click on "Forgot" then on "No account?" you see the register + reset forms => what's the point? I think the "reset" form should only be displayed when the user clicks on "forgot" and be hidden when clicking on "no account" or "have an account".

**Comment by asaunier** [comment]
Thanks for the changes!
Looks good to me.

**Comment by asaunier** [comment]
Feel free to merge @ginold thanks!

**Pull request merged**
