### PR TITLE
Make sure slug redirects use the current scheme

### PR DESCRIPTION
**Pull request by asaunier**
Related to https://github.com/c2corg/v6_ui/issues/981

It works with my localhost (in http - at least ``scheme`` is correctly detected) but I have no https instance for testing. I wonder if it is possible to write some unit tests for this?

### CODE REVIEW

**Comment by asaunier** [comment]
> Maybe you could do this change on the demo server to make sure it works properly.

You mean "by hand"? Not sure I know how to do it :P 

@arnaud-morvan is a code update planned soon (except at golive :P )?

**Comment by asaunier** [comment]
I don't remember exactly why we have replaced ``route_url`` by ``route_path``. Could it cause a wrong hostname to be used here?

**Comment by tsauerwein** [comment]
> I don't remember exactly why we have replaced route_url by route_path. Could it cause a wrong hostname to be used here?

In general `route_path` seems to works, all other links are generated that way (except for the sitemap). But it does not seem to work properly for the redirect in this case.

**Comment by tsauerwein** [comment]
Which makes me wonder, should we generate the sitemap urls with https? That would make sense.

**Comment by asaunier** [comment]
> Which makes me wonder, should we generate the sitemap urls with https? That would make sense.

Sure. Especially since https URLs will be the standard ones (see https://github.com/c2corg/v6_ui/issues/842) and because it seems https pages are better ranked by search engines (?).

**Pull request merged**
