### PR TITLE
[WIP] Add addthis service to the website

### PR DESCRIPTION
**Pull request by dkocich**
related to https://github.com/c2corg/v6_ui/issues/1495

The tool should work correctly just by adding one line but I am not sure about the exact styling and use of all other offered possibilities (please explore https://www.addthis.com/get/share).

Note - all styles, layout, visible button settings, etc. can be change on the addthis website with UI. Added script just loads the current configuration.

I can invite anyone to test and change settings of this account or you can create association's account and change `pubid` of the src attribute now.

Todo:
- [ ] add `pubid` key to the config instead of `base.html` ?

### CODE REVIEW

**Comment by brunobesson** [comment]
@dkocich could you send me an invitation? (although I'm not sure I'll have time to work on this this week)

**Comment by brunobesson** [comment]
I didn't test a lot, awaiting the invitation, but:

* I think we should use the round, expanding button, to be consistent with the other buttons we already use
* I would add this button to the list of already existing button on the right (on tablet and desktop). And mak so that expanded share buttons are displayed in another oclumn on the left of these button (having them a little bit smaller than the "main" buttons would be good IMHO)
* On mobile, I would replace the comments button by the share button (there isn't enough spae for 5 buttons)

**Comment by dkocich** [comment]
> awaiting the invitation

I am sorry, please send me your email address to david.kocich at camptocamp dot com :))

**Comment by brunobesson** [comment]
@dkocich I have made some experiments on the subject (although I didn't really test how share is generated now):

* add custom share links (do not use addthis-generated stuff), and only for guidebook document views
* on mobile, add share item in plus menu
* on tablet and desktop, add share button at the top level
* add some facebook and google specific metadata to customize content (e..g images)

How should I process? Do I build my own branch? Or maybe you are willing to work on it, and I would only provide you with my diff?

**Comment by brunobesson** [comment]
https://github.com/c2corg/v6_ui/tree/addthis-2

**Comment by brunobesson** [comment]
I think we can remove this branch and PR, https://github.com/c2corg/v6_ui/tree/addthis-2 replaces it. Thanks @tsauerwein for the initial work.

**Comment by asaunier** [comment]
> Thanks @tsauerwein for the initial work.

Do you mean @dkocich ? :P 
OK for closing the current branch and PR.

**Pull request closed without merging**
