### PR TITLE
Use - as default slug

### PR DESCRIPTION
**Pull request by asaunier**
Fixes https://github.com/c2corg/v6_ui/issues/809

### CODE REVIEW

**Comment by tsauerwein** [comment]
For my work on the sitemaps, I created a function `get_slug`:

```
--- a/c2corg_ui/views/document.py
+++ b/c2corg_ui/views/document.py
@@ -418,12 +418,9 @@ class Document(object):
             self._redirect(data['redirects_to'], lang, None, is_lang_set)
         else:
             locale = data['locales'][0]
-            title = ''
-            if self._API_ROUTE == 'routes' and locale['title_prefix']:
-                title += locale['title_prefix'] + ' '
-            title += locale['title']
-            self._redirect(data['document_id'], locale['lang'],
-                           slugify(title), is_lang_set)
+            slug = get_slug(locale, is_route=self._API_ROUTE == 'routes')
+            self._redirect(
+                data['document_id'], locale['lang'], slug, is_lang_set)
 
     def _get_interface_lang(self):
         return self.request.cookies.get('interface_lang', self._DEFAULT_LANG)
@@ -442,3 +439,11 @@ class Document(object):
             'document': document
         })
         return self.template_input
+
+
+def get_slug(locale, is_route):
+    title = ''
+    if is_route and locale['title_prefix']:
+        title += locale['title_prefix'] + ' '
+    title += locale['title']
+    return slugify(title)
```

And in this function I would add a check:

```
slug = slugify(title)
if not slug:
     slug = '-'
return slug
```

This way you avoid having `|| '-'` all over the place and prevent that it's forgotten in the future.

**Comment by asaunier** [comment]
Please note slugs are also generated in JS https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/urlservice.js#L58

> For my work on the sitemaps, I created a function get_slug:

What do you suggest? Should I pick your code in this PR?

**Comment by tsauerwein** [comment]
> What do you suggest? Should I pick your code in this PR?

Yes, maybe. I will do a rebase later.

**Comment by tsauerwein** [comment]
Branch updated. Ok for you, @asaunier?

**Comment by asaunier** [comment]
OK for me, thanks
Is it OK to call ``c2corg.view.document`` from the mako templates though?

**Comment by tsauerwein** [comment]
> Is it OK to call c2corg.view.document from the mako templates though?

Yes, it's just importing a function.

**Comment by asaunier** [comment]
OK, please merge when Travis passes.

**Pull request merged**
