### PR TITLE
View archived document version

### PR DESCRIPTION
**Pull request by asaunier**
as well as some changes in the history page

### CODE REVIEW

**Comment by asaunier** [comment]
The PR is ready for reviewing.

Please note that clicking on button "Compare selected versions" does not actually work as expected since the diff page is not available yet.

**Comment by gberaudo** [comment]
+1

**Comment by asaunier** [comment]
Thanks @gberaudo !
OK for you @tsauerwein ?

**Comment by tsauerwein** [comment]
I didn't do an in-depth review, but feel free to merge.

**Comment by asaunier** [comment]
OK thanks @tsauerwein  That's not an advanced PR anyway: a simple Angular directive/controller for managing the radio buttons and a small piece of mako template. As I say the "compare" function in ``VersionsController`` will have to be updated to open one of your diff page URL.
Merging.

**Pull request merged**
