### PR TITLE
display boolean values as yes/no

### PR DESCRIPTION
**Pull request by ginold**
related to #978

+ public transport
+ partial trip

@desnoes  @stef74 do you know any places on any document page where any other value is displayed "True" or "None" instead of "yes" and "no?

### CODE REVIEW

**Comment by desnoes** [comment]
i did exhausive tests for all the fieds defined for all kinds of routes and WPs. I did not find other cases.than the ones reported in the issue.

----- Mail original -----
De: "Adam Gina" <notifications@github.com>
À: "c2corg/v6_ui" <v6_ui@noreply.github.com>
Cc: "desnoes" <mathieu.desnoes@free.fr>, "Mention" <mention@noreply.github.com>
Envoyé: Jeudi 15 Décembre 2016 15:42:32
Objet: [c2corg/v6_ui] display boolean values as yes/no (#1225)



related to #978 

    * public transport 
    * partial trip 


@desnoes @stef74 do you know any places on any document page where any other value is displayed "True" or "None" instead of "yes" and "no? 
You can view, comment on, or merge this pull request online at: 


https://github.com/c2corg/v6_ui/pull/1225 Commit Summary 


    * display boolean values as yes/no 
File Changes 


    * M c2corg_ui/templates/outing/helpers/view.html (6) 
    * M c2corg_ui/templates/route/helpers/view.html (2) 
    * M c2corg_ui/templates/waypoint/helpers/view.html (5) 
Patch Links: 


    * https://github.com/c2corg/v6_ui/pull/1225.patch 
    * https://github.com/c2corg/v6_ui/pull/1225.diff

**Comment by stef74** [comment]
@lbesson @loicperrin do you identifed other content have true/none ?

**Comment by lbesson** [comment]
why me? :)

**Comment by brunobesson** [comment]
@lbesson why not? :stuck_out_tongue:

**Comment by stef74** [comment]
sorry I want to add @bruno

2016-12-15 17:42 GMT+01:00 Lionel Besson <notifications@github.com>:

**Comment by brunobesson** [comment]
why me? :wink: 
but no, I don't remember having seen something else.

**Comment by ginold** [comment]
Ok, thank you for the investigation. I will merge this PR soon.

**Pull request merged**
