### PR TITLE
Add the map mouseWheel interaction back

### PR DESCRIPTION
**Pull request by asaunier**
- MouseWheel is disable when scrolling the page unless the cursor
stops on the map for >500ms (credits go to @tsauerwein).
- It is possible to fully disable the mouseWheel interaction using
an `app-map-disable-wheel` attribute.

Based upon and fixes https://github.com/c2corg/v6_ui/issues/189

### CODE REVIEW

**Comment by asaunier** [comment]
Please review :)

**Comment by asaunier** [comment]
@tsauerwein is this PR OK for you or did you think of something else?
I have somehow only copied-pasted your example code :P

**Comment by tsauerwein** [comment]
Small comment, besides that looks fine!

**Comment by tsauerwein** [comment]
Thanks!

**Comment by asaunier** [comment]
Thanks for the tip and review @tsauerwein !
Waiting for Travis to greenlight before merging.

**Pull request merged**
