### PR TITLE
Better doctype selector in advanced search pages

### PR DESCRIPTION
**Pull request by asaunier**
Related to https://github.com/c2corg/v6_ui/issues/1162

TODO

* [x] propagate the current bbox or selected areas if relevant
* [x] propagate selected activities if relevant

### CODE REVIEW

**Comment by asaunier** [comment]
This PR has just been updated: it adds a new ``app-doctype-selector`` directive that replaces the mako helper ``add_doctype_selector``.

The apparent behaviour is the same except that parameters ``bbox``, ``a`` (areas) or ``act`` (activities) are propagated to the target advanced search page if available and relevant.

Please review :)

**Comment by brunobesson** [comment]
I tried to checkout your branch, but when switching from outings to waypoints in the combobox, I get a 

    Uncaught ReferenceError: doctypeCtrl is not defined at HTMLSelectElement.onchange

related to `doctypeselector.html`

**Comment by asaunier** [comment]
The branch you use is outdated. This is the error that came with the original version of the branch, a month ago.

To get the very last version of the branch you may type:
```
git fetch
git checkout doctype-selector-directive
git reset --hard origin/doctype-selector-directive
```

**Comment by brunobesson** [comment]
OK... I don't understand why because I did a git fetch. Maybe I only forgot to pull updates to the branch? Whatever. Seems to be working now. I might not be the best fitted for a code review, but my tests show it is working as adverted.

**Comment by asaunier** [comment]
Probably because I did a "push force" (push -f) since my branch was rebased. I think a "git fetch" is not enough to get the final branch since the branch had diverged.
Perhaps in that case a "git fetch" or "git pull" reports the divergence?

**Comment by asaunier** [comment]
@brunobesson Thanks for the review and testing! I'll merge the PR this afternoon if no one else objects in the meantime or ask for more time.

**Pull request merged**
