### PR TITLE
 Add Text in the middle feature support & test

### PR DESCRIPTION
**Pull request by olaurendeau**
New PR, same as https://github.com/c2corg/v6_ui/pull/1824 with squashed commits & origin branch

Given the result for that much complexity added to the code, I'm not sure that I've properly understood the original purpose of tag `L#~`. Documentation didn't helped me that much ^^ https://www.camptocamp.org/articles/305462/fr/aide-topoguide-l-balise-de-description-des-longueurs

Markdown

``` 
## Approche
Du pont sur le Tramouillon revenir vers le village et prendre immédiatement à gauche une sente qui monte vers la falaise du Ponteil. Prendre une sente vers la partie droite de la falaise. Noms indiqués au pied des voies sur une vire. Départ commun avec [[routes/57140|Yakafokon]].

## La voie

L# | 5b+ | tout droit, courte longueur à enchaîner avec L2 (Yakafokon part à droite)

L# | 6a+ | un petit toit (pas de bloc) puis un dièdre court et technique.

L# | 6a | traverse à gauche, remonte un dièdre et retraverse à gauche les pieds dans une dalle patinée pour contourner un toit.

L#~ Texte.
Retour à la ligne possible.

Saut de ligne possible en ajoutant au moins un espace dans la ligne vide.
Les sous-titres et les listes ne sont pas acceptés.

L# | 6a | tout droit, court passage athlétique puis facile pour rejoindre un dièdre puis une traversée en dalle sous un gros toit.

L# | 6b+ | contourne le toit par la gauche, athlétique et soutenu ; très bien protégé.

L# | 6a | un pas à gauche puis tout droit dans un dièdre évasé pour sortir sur une large vire.

Descendre de quelques mètres sur la vire pour trouver la dernière longueur.

L# | 5c | grande longueur en ascendance à droite dans un système de dièdres/blocs puis dalle à silex.

## Descente
On peut rejoindre la sortie de Nid d'Aigle 50m à droite en sortant de la voie. Une corde statique permet d'accéder au premier rappel. 
- Corde de 2*50m : trois rappels. 
- Corde de 2*60m : deux rappels (le premier faisant 58m).

On peut aussi emprunter les rappels situés 30m à droite de la Martine : premier rappel de 40m sur un arbre, puis un deuxième de 40m sur chaîne.
```

HTML
```
<div class="ficontent collapse max in">
  <summary class="document-summary">
      
      <p>Très belle ambiance aérienne, face courte mais soutenue.</p>
  </summary>

  
  <h3 id="approche">Approche</h3>
  <p>Du pont sur le Tramouillon revenir vers le village et prendre immédiatement à gauche une sente qui monte vers la falaise du Ponteil. Prendre une sente vers la partie droite de la falaise. Noms indiqués au pied des voies sur une vire. Départ commun avec <a href="/routes/57140">Yakafokon</a>.</p>
  <h3 id="la-voie">La voie</h3>
  <table class="ltag">
    <tbody>
        <tr>
            <td><span class="pitch"><span translate=""><span class="ng-scope">L</span></span>1</span></td>
            <td>5b+</td>
            <td>tout droit, courte longueur à enchaîner avec L2 (Yakafokon part à droite)</td>
        </tr>
        <tr>
            <td><span class="pitch"><span translate=""><span class="ng-scope">L</span></span>2</span></td>
            <td>6a+</td>
            <td>un petit toit (pas de bloc) puis un dièdre court et technique.</td>
        </tr>
        <tr>
            <td><span class="pitch"><span translate=""><span class="ng-scope">L</span></span>3</span></td>
            <td>6a</td>
            <td>traverse à gauche, remonte un dièdre et retraverse à gauche les pieds dans une dalle patinée pour contourner un toit.</td>
        </tr>
        <tr>
            <td colspan="4">Texte.<br>Retour à la ligne possible.<br>Saut de ligne possible en ajoutant au moins un espace dans la ligne vide.<br>Les sous-titres et les listes ne sont pas acceptés.</td>
        </tr>
        <tr>
            <td><span class="pitch"><span translate=""><span class="ng-scope">L</span></span>4</span></td>
            <td>6a</td>
            <td>tout droit, court passage athlétique puis facile pour rejoindre un dièdre puis une traversée en dalle sous un gros toit.</td>
        </tr>
        <tr>
            <td><span class="pitch"><span translate=""><span class="ng-scope">L</span></span>5</span></td>
            <td>6b+</td>
            <td>contourne le toit par la gauche, athlétique et soutenu ; très bien protégé.</td>
        </tr>
        <tr>
            <td><span class="pitch"><span translate=""><span class="ng-scope">L</span></span>6</span></td>
            <td>6a</td>
            <td>un pas à gauche puis tout droit dans un dièdre évasé pour sortir sur une large vire.</td>
        </tr>
    </tbody>
</table>
<p>Descendre de quelques mètres sur la vire pour trouver la dernière longueur.</p>
<table class="ltag">
    <tbody>
        <tr>
            <td><span class="pitch"><span translate=""><span class="ng-scope">L</span></span>7</span></td>
            <td>5c</td>
            <td>grande longueur en ascendance à droite dans un système de dièdres/blocs puis dalle à silex.</td>
        </tr>
    </tbody>
</table>
<h3 id="descente">Descente</h3>
<p>On peut rejoindre la sortie de Nid d'Aigle 50m à droite en sortant de la voie. Une corde statique permet d'accéder au premier rappel. <br>
    - Corde de 2<em>50m : trois rappels. <br>
    - Corde de 2</em>60m : deux rappels (le premier faisant 58m).</p>
    <p>On peut aussi emprunter les rappels situés 30m à droite de la Martine : premier rappel de 40m sur un arbre, puis un deuxième de 40m sur chaîne.</p>
</div>
```

Result
capture d ecran 2017-11-20 a 22 57 28

### CODE REVIEW

**Comment by olaurendeau** [comment]
Original comment from @asaunier 

> Thanks @olaurendeau !
> 
> I only had a quick look but have seen no problem with your changes except that the API switch to HTTPS is no longer needed (a fix has been pushed in the meantime) and that you probably don't really want to disable redis: please remove the first 2 commits 
> 6cdd2df and 629fb10
> 
> In addition many of your commits are only fixes/additions to previous commits. You may of course "squash and merge" the commits when merging the PR but it's cleaner for reviewers to already have the commits tidy in the PR.
> 
> 2 options:
> * when doing your commits, you can assign new changes to the last commit by "amending" it: simply "git add" your changes + "git commit --amend" them.
> * to reorganize your commits (remove/group/rename/reorder some of them) you have to use the interactive rebasing command: "git rebase -i". See the tutorial here: https://github.com/c2corg/v6_ui/wiki/Git-Cookbook#managing-commits
> 
> Last, I would recommend that you pushed your branch to the main repository, not in your fork. This way a docker image is automatically generated (if the tests pass) and made available at https://hub.docker.com/r/c2corg/v6_ui/tags/ => we can then deploy your work on the demo to have it tested for real.

**Comment by olaurendeau** [comment]
Hello @asaunier 

- Branch is pushed on origin
- Commit reorganised
- I kept the redis param modification, because redis was already disabled by default (else in dev you would permanently hit the cache and not see your modification), but with the url defined in configuration, it was slowing down the dev application.

**Comment by asaunier** [comment]
@olaurendeau Thank you very much!

I have no clue about your docker changes: does it mean redis is disabled in dev mode?

Concerning the L#, both your changes in the code and the results in my own instance look good to me.
@fbunoz @cbeauchesne Could you confirm that the ``L#~`` is converted as expected? See the examples and screenshot in the initial comment above. Thanks!

**Comment by cbeauchesne** [comment]
It's ok for me. Do we plan to have it on a demo server? By the way, I'm pretty confident that it's ok.

**Comment by asaunier** [comment]
> Do we plan to have it on a demo server?

Not before the PR is merged, unless it is really wanted to intensively test the branch.

**Comment by olaurendeau** [comment]
Thanks for your reviews ! 👍

Regarding docker, redis is already disable in the current version https://github.com/c2corg/v6_ui/blob/master/docker-compose.yml#L15-L21 issue is the redis url is still define here https://github.com/c2corg/v6_ui/blob/master/docker-compose.yml#L8 so the UI is trying to store the generated page in redis, slowing down the global response time.

**Comment by olaurendeau** [comment]
@asaunier I just realize after merging, that I've added an info log here https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/format/ltag.py#L42. What is the log level configured in production ? Should I lower it down to `debug` ?

**Comment by asaunier** [comment]
> What is the log level configured in production ? Should I lower it down to debug ?

I don't know. But I think no other occurence of ``log.info``, it seems we rather use ``log.debug``.
It depends if we want to have the unsupported tags reported in the logs.

**Comment by olaurendeau** [comment]
Well it could be useful to choose which tags to prioritize next, but it also can generate quite a lot of logs, if logs are stored in files on production server it could be an issue. Of course when page is cached in redis log won't be generated again.

For example when displaying the page of [Aiguille de la République : Republique bananière](http://localhost:6553/routes/57964/fr/aiguille-de-la-republique-republique-bananiere) which contain a lot of unsupported tags it will generate the following logs
```
ui_1  | 2017-11-29 09:41:15,943 INFO  [c2corg_ui.format.ltag][waitress] Skip all because of unsupported LTAG : "L#+gauche | 6c | | | Partir dans la dalle \xe9quip\xe9e \xe0 droite. | Relais sur la grande rampe qu&#x27;emprunte les itin\xe9raires classiques de Gr\xe9pon-Mer de glace et la VN de la R\xe9publique. "
ui_1  | 2017-11-29 09:41:15,944 INFO  [c2corg_ui.format.ltag][waitress] Skip all because of unsupported LTAG : "L#droite | 5c | | 2 spits | D\xe9buter par un di\xe8dre puis une dalle et enfin en ascendance droite | Relai possible et conseill\xe9 10m plus loin sur un bloc ceintur\xe9 de sangles."
ui_1  | 2017-11-29 09:41:15,944 INFO  [c2corg_ui.format.ltag][waitress] Skip all because of unsupported LTAG : "L#_ | 5b | | pitons | Monter droit au dessus du bloc \xe0 droite d&#x27;un triangle rocheux (IV+) sur environ 15m puis traverser 5-6m \xe0 droite et remonter vers la gauche des dalles faciles entrecoup\xe9es de courts ressaut (V). | Relai sur une terrasse."
ui_1  | 2017-11-29 09:41:15,945 INFO  [c2corg_ui.format.ltag][waitress] Skip all because of unsupported LTAG : "L#13 | 6b+ | 53m |  | La longueur transcendentale. En plein dans le di\xe8dre | Relai sur une bonne vire."
ui_1  | 2017-11-29 09:41:15,945 INFO  [c2corg_ui.format.ltag][waitress] Skip all because of unsupported LTAG : "L#bis |  |  |  | De R#-1 rep\xe9rer 30m plus bas une terrasse avec un spit. Descendre en rappel vers la terrasse, puis grimper un peu par une fissure (IV+) \xe0 droite de la terrasse (assur\xe9 par le rappel)."
ui_1  | 2017-11-29 09:41:15,946 INFO  [c2corg_ui.format.ltag][waitress] Skip all because of unsupported LTAG : "L#_ | 6a+ |  |  | Un court di\xe8dre, une traverse \xe0 droite puis une fissure exigeante. Rochers faciles ensuite. Rester \xe0 gauche du couloir. Gagner une br\xe8che par un di\xe8dre facile. | Relai sur un spit au niveau de gros blocs."
ui_1  | 2017-11-29 09:41:15,947 INFO  [c2corg_ui.format.ltag][waitress] Skip all because of unsupported LTAG : "L#bis | marche | 50m |  | Remonter le couloir. | Relai au pied du di\xe8dre. S&#x27;il y a une vieille accumulation de neige, utiliser le relai en rive gauche 10m en contrebas."
ui_1  | 2017-11-29 09:41:15,948 INFO  [c2corg_ui.format.ltag][waitress] Skip all because of unsupported LTAG : "L#_ | 6b+ |  | | Dans le magnifique di\xe8dre | Relai sur une terrasse."
```

**Comment by asaunier** [comment]
I don't really have an opinion and don't know if having many entries in the logs could be a problem and if we could easily take advantage of those logs to figure out what LTAGs should be managed in priority.

**Pull request merged**
