### PR TITLE
Add health web-service

### PR DESCRIPTION
**Pull request by tsauerwein**
See also https://github.com/c2corg/v6_api/pull/499

Example:

```
{
	"version": "458187d",
	"redis": "ok",
	"api": "ok",
	"redis_keys": 33,
	"api_status": {
		"pg": "ok",
		"es_indexed_docs": 0,
		"es": "ok",
		"redis_keys": 13025,
		"last_es_syncer_run": "2016-11-11T12:27:52.023859+01:00",
		"redis": "ok",
		"version": "15fbece"
	}
}
```

### CODE REVIEW

**Comment by asaunier** [comment]
How would you see this ``health`` service used in the UI?
Having the version displayed somewhere in the pages would make sense, but shouldn't this info be integrated in mako templates (eg. in ``base.html``) and cached? Then do we need a UI webservice?

**Comment by tsauerwein** [comment]
The aim of this PR was not to show a version in the pages. This health web-service is for developers to verify the deployed version and to get information about the status. Also it can be used for monitoring purposes.

**Comment by asaunier** [comment]
OK

But when @mfournier suggested to get the current version
> Which returns the current revision (proposed by @mfournier).

I think he considered showing the current version in the pages, so that tested may know the revison of the demo.

So I am just wondering if the ``health`` services could be used for that purpose.

Anyway OK for merging, thanks!

**Comment by tsauerwein** [comment]
Ok, I pushed a commit to show the version in the sidebar. The links points to Github.

c2corg-version

**Comment by asaunier** [comment]
OK, I understand, thanks.

I wonder if this info could not be placed somewhere else. It's useless for most visitors and the current position uses space in the sidemenu and will make the ad banner disappear for even smaller screens (when there is not enough space to show the ad banner it is removed).

**Comment by tsauerwein** [comment]
I'll let you figure this out. Feel free to drop/adapt the last commit.

**Comment by asaunier** [comment]
Please merge as is, I don't really have time/inspiration/skills to propose something else :P

**Comment by tsauerwein** [comment]
I reduced the alpha value of the color a bit, to make it less prominent:

c2corg-version

**Pull request merged**
