### PR TITLE
Add first unit tests

### PR DESCRIPTION
**Pull request by asaunier**
Still very basic :P 

I have copied/pasted tests from the API and removed all DB-related code since the UI has no DB connection.

### CODE REVIEW

**Comment by asaunier** [comment]
Looks good?

**Comment by asaunier** [comment]
What other tests could be added?

**Comment by tsauerwein** [comment]
Yes, looks good!

Are you already making calls to the REST API from the Travis tests?

**Comment by asaunier** [comment]
> Are you already making calls to the REST API from the Travis tests?

No, but I will add such tests. Thanks for the suggestion.

**Comment by asaunier** [comment]
> Are you already making calls to the REST API from the Travis tests?

The problem is that we cannot use a travis-created API to make test calls since the API is a separated app. Does this mean that we have to maintain a demo API app on some server and make travis request it through the UI tests?

I think such tests may be added in a new PR. Merging the current one as is.

**Pull request merged**
