### PR TITLE
limit card size in feed

### PR DESCRIPTION
**Pull request by stef74**
To limit image distortion et too wide card.
It's not enough to improve globaly but simple in 1st approach.

### CODE REVIEW

**Comment by brunobesson** [comment]
Wouldn't that accentuate the furstration of those having a wide screen which will now have even more green empty space?

**Comment by stef74** [comment]
Not because you have blank space in card ... information density not change
... only image are more correct (currently in very large screen image are
not usable in feed).
Is no an optimal solution ... but it's better than existing solution.

2017-02-24 14:10 GMT+01:00 Bruno Besson <notifications@github.com>:

**Comment by asaunier** [comment]
Does it impact the profile feed too?
I have noticed the the profiles in the home and profile pages had not the same width, which is not consistent. Will this PR fix this inconsistency?

**Comment by stef74** [comment]
@asaunier not is font size issue. I have try to manage in https://github.com/c2corg/v6_ui/pull/1379

**Comment by stef74** [comment]
An other way is to limit only image (that is the problem in fact). 
current screen width : 2500px


new one 
capture d ecran 2017-02-26 a 17 54 38


An evolution can be add more photo ... but it's an other job !

**Pull request closed without merging**
