### PR TITLE
[WIP] Add guidebook homepage

### PR DESCRIPTION
**Pull request by asaunier**
Related to https://github.com/c2corg/v6_ui/issues/254

At least a basic version. Some work is still needed for fixing the styles and have a nice layout but I don't feel skilled enough.

Some other cards (shortcuts? activities?) would probably be relevant too.

Question: I have used "guidebook" as page path + in the filenames etc. Should it rather be "topoguide", in order to be consistent with the menu and the page title? (In the API I think we use "guidebook").

capture d ecran 2016-11-05 a 19 08 48

### CODE REVIEW

**Comment by tsauerwein** [comment]
The hacky code that I used for the mockup is in this branch: https://github.com/c2corg/v6_ui/tree/guidebook-homepage

**Comment by asaunier** [comment]
> The hacky code that I used for the mockup

OK, https://github.com/c2corg/v6_ui/commit/7c996be0ab623be44cd630764bed5c56452b2294

Argh, I had not checked if you had pushed some code anywhere. No big deal: I have not spend hours on mine and both proposals need to be reworked anyway.

Where do the image in your branch come from? Is it allowed to use them?

**Comment by tsauerwein** [comment]
> Where do the image in your branch come from? Is it allowed to use them?

All images are from the [Concours Photo Sophie 2016](http://www.camptocamp.org/articles/809627/fr/concours-photo-sophie-2016).

**Comment by asaunier** [comment]
Closing since replaced by https://github.com/c2corg/v6_ui/pull/1243

**Pull request closed without merging**
