### PR TITLE
Provide sso for discourse

### PR DESCRIPTION
**Pull request by gberaudo**
Forward discourse sso and signature to API.
Redirect to forum after successful login.

### CODE REVIEW

**Comment by tsauerwein** [comment]
Can you explain a bit the whole login procedure? I would have thought that Discourse itself calls `api.c2c.org/sso?sso=PAYLOAD&sig=SIG`?

**Comment by gberaudo** [comment]
Discourse passes the sso and sig parameters to the login page of the UI; see adaptation of UI at https://github.com/c2corg/v6_api/pull/118.
Then the user logs to the API and at the same time the user information is signed for discourse and returned.
The UI redirects to discourse, passing this information.
The user is logged both on the UI and forum.

**Comment by asaunier** [comment]
Creating a README page explaining how Discourse SSO is implemented in the project would be useful I think.

**Comment by gberaudo** [comment]
You can now test on the demo server: http://c2corgv6-discourse.demo-camptocamp.com/

**Comment by gberaudo** [comment]
Sure @asaunier, I will put documentation on https://github.com/c2corg/v6_forum

**Comment by asaunier** [comment]
> You can now test on the demo server: http://c2corgv6-discourse.demo-camptocamp.com/

Seems to work indeed: when I open the page above and click on the "login" button I get redirected to the usual login page on the UI site. After logging in in the latter page I get redirected to the forum where I am actually authenticated.

You probably already know but:
- if I click on "logout" in the forum page, I am not logged out in the UI site
- if I log in in the UI site without coming from the forum, I am then not authenticated in the forum page

**Comment by gberaudo** [comment]
Sure, I created #79 for tracking progress on this.

**Comment by gberaudo** [comment]
Documentation in https://github.com/c2corg/v6_forum/blob/master/README.md

**Comment by tsauerwein** [comment]
Thanks for the explanation, your changes look good to me.

**Comment by gberaudo** [comment]
Thanks for the review.

**Pull request merged**
