### PR TITLE
Svg less fix

### LINKED ISSUE #634: Inversion of picto
At least in the route creation formulaire, the pictos 'Rocher haute montagne' and 'escalade' are inverted.

### PR DESCRIPTION
**Pull request by ginold**
related to #634
now you tell me if it's ok :)
screenshot from 2016-09-20 11 14 14

### CODE REVIEW

**Comment by asaunier** [comment]
> now you tell me if it's ok :)

That's correct.

It seems that it's not that simple to switch icons. Is there a way to know what "content" is what icon?

Please merge when Travis is OK.

**Comment by ginold** [comment]
> Is there a way to know what "content" is what icon?

no way. It's a randomly generated string when creating the font.

**Comment by asaunier** [comment]
Then how do you know what content to use?

**Comment by ginold** [comment]
I copy-pasted, inverted the existing contents :P

**Pull request merged**
