### PR TITLE
Map editing fixes

### PR DESCRIPTION
**Pull request by asaunier**
- draw only one line (route/outing) at a time
- add a reset button to restore the initial feature

Fixes https://github.com/c2corg/v6_ui/issues/354

Please review!

### CODE REVIEW

**Comment by asaunier** [comment]
OK for merging?

**Comment by asaunier** [comment]
OK for merging?

**Comment by tsauerwein** [comment]
:+1:

**Comment by asaunier** [comment]
Thanks @tsauerwein :)

**Pull request merged**
