### PR TITLE
[#1690] Fix skip behavior, skipping all document after rendering a skipped one

### PR DESCRIPTION
**Pull request by olaurendeau**
Fixing #1690

### CODE REVIEW

**Comment by asaunier** [comment]
@olaurendeau The code change is OK for me.

I have updated the demo to make it use your branch (a docker image has been auto generated https://hub.docker.com/r/c2corg/v6_ui/tags/). I have also switched redis off to prevent caching.

At first sight it seems to work but we probably need to have more people testing @desnoes

**Comment by desnoes** [comment]
@olaurendeau : thank for the bug fixing !
@asaunier: tell me when the release is available on demo

**Comment by asaunier** [comment]
> when the release is available on demo

It is.

**Comment by desnoes** [comment]
@asaunier : ok i will test this evening

**Comment by olaurendeau** [comment]
Look good to me :)
Thanks for fast feedback !

**Comment by desnoes** [comment]
@asaunier : ok for me

**Pull request merged**
