### PR TITLE
Font size reduction

### PR DESCRIPTION
**Pull request by stef74**
related to #1309

### CODE REVIEW

**Comment by brunobesson** [comment]
Could you post a picture to get a visual at the changes you made? :pray:

**Comment by stef74** [comment]
yes let just me upload ;-)

**Comment by stef74** [comment]
capture d ecran 2017-01-05 a 21 06 33
capture d ecran 2017-01-05 a 21 07 24

**Comment by brunobesson** [comment]
OK for me, I won't ask for screenshots on tablet or phone :wink:

**Comment by stef74** [comment]
capture d ecran 2017-01-05 a 21 25 57
capture d ecran 2017-01-05 a 21 30 39

**Comment by brunobesson** [comment]
Thanks for this :+1: 
And it's a good idea, because to me, the icons are now too small for mobile and tablets, especially for mobile: I would rather use a size equal to that of the edit buttons. What do you think?

**Comment by stef74** [comment]
For tablet is enough for me ... for mobile I'm agress is little too small (probably remove text is an good idea but ouf my competencies)

**Comment by stef74** [comment]
new version 
capture d ecran 2017-01-05 a 21 46 34
capture d ecran 2017-01-05 a 21 48 25

**Comment by asaunier** [comment]
I don't know why but I see no difference with the prod when testing this PR, at various screen width. I have made sure my cache was cleared though. With Chrome and FF.

**Comment by stef74** [comment]
could you provide your CSS file

2017-01-06 12:45 GMT+01:00 Alex Saunier <notifications@github.com>:

**Comment by stef74** [comment]
I have probably found ... i have edit documentedit.less ... but i hav other faile contain "same" content : https://github.com/c2corg/v6_ui/blob/d5f6cad0a7af9c7c1fbcf661b60f9d2c250569bf/less/c2corg_ui.less#L928

**Comment by stef74** [comment]
why travis fails ? (i don't understand the log ...)

**Comment by stef74** [comment]
Add a fix to snowcraft condition and activites are little more big than other text

**Comment by stef74** [comment]
reduction of orientation 
capture d ecran 2017-01-08 a 20 43 38
capture d ecran 2017-01-08 a 20 44 08

**Comment by stef74** [comment]
in edition : 
capture d ecran 2017-01-08 a 20 48 18
capture d ecran 2017-01-08 a 20 50 04

**Comment by tsauerwein** [comment]
> why travis fails ? (i don't understand the log ...)

Please rebase your branch with master. It is related to https://github.com/c2corg/v6_ui/pull/1316.

**Comment by brunobesson** [comment]
Your changes look fine to me, except for the wind roses in edition: you have reduced its size (which is fine for me, although I think we should rework it to make it more usable and readable, but it is another issue), but not the space around. Having half the place for the wind roses and half the place for the route type and configuration does not the best option now, IMHO.

**Comment by brunobesson** [comment]
>Merge remote-tracking branch 'refs/remotes/origin/master' into font-size

This is not the best way to rebase :stuck_out_tongue:

**Comment by stef74** [comment]
Tonight I recreate a proper branch with remove commit concerning orientation.

**Comment by brunobesson** [comment]
>Tonight I recreate a proper branch with remove commit concerning orientation.

OK, it's true that it's mostly handled by #1332 (or otherwise could be another PR). Other than that I think we'll be able to squash the PR.

**Pull request merged**
