### PR TITLE
Addthis integration

### PR DESCRIPTION
**Pull request by brunobesson**
Some time ago, I continued @dkocich work on addthis integration.
I cannot test it fully because the referred URL is localhost. But I am pretty confident we should at least have some results. @asaunier would you accept we merge this PR and test it on the demo? How did you do it for @Courgetteandratatouille when... I don't remember why, but you did something similar.

### CODE REVIEW

**Comment by brunobesson** [comment]
c2c12
c2c13

(I'll make corrections to add an icon to share link)

**Comment by asaunier** [comment]
> would you accept we merge this PR and test it on the demo? How did you do it for @Courgetteandratatouille when... I don't remember why, but you did something similar.

It's possible to deploy whatever branch's docker image on the demo when it's available on https://hub.docker.com/r/c2corg/v6_ui/tags/ (Travis will build it after running the tests etc.). I'll upgrade the demo with this branch when the image is ready.

**Comment by asaunier** [comment]
Travis reports an error:
>   File "/home/travis/build/c2corg/v6_ui/c2corg_ui/templates/profile/view.html", line 39, in render_share
    ${generate_share_metadata(profile, 'profiles')}
  File "/home/travis/build/c2corg/v6_ui/c2corg_ui/templates/helpers/view.html", line 935, in render_generate_share_metadata
    % if document_type != 'images' and document.get('associations').get('images'):
AttributeError: 'NoneType' object has no attribute 'get

**Comment by brunobesson** [comment]
>Travis reports an error

OK, there must be no associations for a profile. I'll make a correction.

**Comment by asaunier** [comment]
@brunobesson I have updated the demo with your branch.

**Comment by brunobesson** [comment]
OK, thanks @asaunier!
I tested it and it seems to be OK. I'll merge this PR (after your review?), you can switch back to master or the previous release for the demo.

**Pull request merged**
