### PR TITLE
Urlencode filters values when added into the address bar

### PR DESCRIPTION
**Pull request by asaunier**
Related to https://github.com/c2corg/v6_ui/issues/742

PR created just for the records (it was ready) since a change in ngeo is pending: https://github.com/camptocamp/ngeo/pull/2002

### CODE REVIEW

**Comment by tsauerwein** [comment]
If you want, we can use this PR as long as ngeo is not updated.

**Comment by asaunier** [comment]
It depends how long it will take before your PR is merged and if we have problems upgrading ngeo/OL in v6_ui.

That could be a temporary fix, yes, especially since the beta probably needs a fast fix.

**Comment by asaunier** [comment]
@tsauerwein Your PR in ngeo has been approved (question from @gberaudo though?). Do you think it will be merged soon?
That we could upgrade our ngeo/OL soon?

Just trying to figure out it's better whether to merge my current PR now and revert it when your PR is merged + ngeo/OL are upgraded or to wait a bit?
If it can be done today it's worth waiting. Else I would prefer to merge my PR so that the demo has at least a temporary fix.

**Comment by tsauerwein** [comment]
> @tsauerwein Your PR in ngeo has been approved (question from @gberaudo though?). Do you think it will be merged soon?
> That we could upgrade our ngeo/OL soon?

I will merge the ngeo PR once Travis has passed and can then look into updating ol/ngeo.

**Comment by asaunier** [comment]
No longer needed since done in ngeo.

**Pull request closed without merging**
