### PR TITLE
Associated data design

### PR DESCRIPTION
**Pull request by brunobesson**
References #966 

Now, with simple inner card and scrollable content:
after

(and of course, collapses nicely now)

### CODE REVIEW

**Comment by asaunier** [comment]
Do you really need 3 commits for such a change?
OK the commit can be squashed when merging, but it's better to drop useless commits/changes before the review :)

**Comment by brunobesson** [comment]
I know, I should remove those useless commits... But I do not master git enough yet to do that....

But when you're OK, I'll do the squashing, promise!

**Comment by asaunier** [comment]
I notice that the 2 first commits are provided in many of your recent PRs. Correct?
Are they needed in all those PR?
If yes perhaps it's better to keep the commits distinct and to drop them when they have been integrated by the first merged PR. Else you might have to fix conflicts I think.

**Comment by brunobesson** [comment]
It's a commit I mistakenly made on master branch, then cancelled. Those two commits are useless. I need to have a look on how to rewrite history for this, I'll try tomorrow.

**Comment by ginold** [comment]
Have a quick look if it does impact the associated documents on editing pages, and if it does - if 
that is what we want.

Else, it looks smoother indeed!

**Comment by brunobesson** [comment]
I have check there is no impact on editing pages, so merging this PR.

**Pull request merged**
