### PR TITLE
Handle validation of registration email

### PR DESCRIPTION
**Pull request by gberaudo**
At the end of the process, the registration is completed and
the user logged in.

Useful with https://github.com/c2corg/v6_api/pull/190.

### CODE REVIEW

**Comment by asaunier** [comment]
As far as I can see it works the way you described me last week: when a new user clicks on the link in the validation email message it is then directly logged in without having to enter his username/password.
Correct?

**Comment by asaunier** [comment]
And the "password forgotten" feature would work the same: one would receive an email with a link to click that would log him in instead of receiving a new email. Still correct?

**Comment by gberaudo** [comment]
Yes in both cases the user is directly logged in.

**Comment by asaunier** [comment]
Looks good to me

**Pull request merged**
