### PR TITLE
reduce card font-size + larger cards treshold

### PR DESCRIPTION
**Pull request by ginold**
related to #1186
screenshot from 2016-12-13 12-53-33

+ 3 cards per row for >2000px screens width
+ 2 cards per row default
+ 1 card per row for < 800px screens width
+ 90% card font size (super small imho)

Should this change be applied only to the advanced search lists? or also to associated documents in views/editing pages?

### CODE REVIEW

**Comment by stef74** [comment]
to be more consistent apply also in association

Could you provide a screenshoot on outings please

**Comment by stef74** [comment]
For me the goal is to have 2 lines per card ... if you have same number of line as previsous no interesset

**Comment by stef74** [comment]
push icon activity at the right

**Comment by ginold** [comment]
Ok, changes work everywhere:

View page:

screenshot from 2016-12-13 13-17-13


Editing page: 

screenshot from 2016-12-13 13-17-31


Outings advanced search:

screenshot from 2016-12-13 13-17-53

Icons on the right would look like this (weird imho):

screenshot from 2016-12-13 13-19-19

Is this ok for you @stef74 ? @asaunier  ?

**Comment by stef74** [comment]
For the last screenshot could you try to one column ... and move icon at same level of texte. Keep in mind they are missing some infos.

**Comment by ginold** [comment]
having the icon next to the text is a very bad idea because there might be 2-4 activities which take the whole card width, and the title can be really long too. 
It would maybe work for most of the route cards with short title and 1 activity, but not for the others.

**Comment by stef74** [comment]
something like this
test_card

So probaly enlarge again the card. Currently thet missing some element so some space are need in card.

**Comment by ginold** [comment]
as i said, __maybe__ it would work with short titles and 1 activity, but with more than that you have to expect glitches, getting the card larger is not the best solution.

screenshot from 2016-12-13 13-49-23
screenshot from 2016-12-13 13-49-49

**Comment by stef74** [comment]
You can consider the right of card is column with icon as you do for outing in the feed. Like this 
sans titre

So we need to work on 1 column

**Comment by stef74** [comment]
Cou can reduce black badge ... many complain that is too big.

**Comment by stef74** [comment]
2871c50c-c13b-11e6-9b57-51ef4295f60e

**Comment by ginold** [comment]
That sounds pretty difficult and challenges completely the actual layout. 

In any case, if we want to pursue this change, I would prefer to do it in a separate pull request because it has nothing to do with the issue it tries to solve.

**Comment by desnoes** [comment]
For the outings, it would be good to put on the same line: date, author and region (area). I think there is enough space. This would same one line.

**Comment by stef74** [comment]
Ok do that, you proposition is not bad ... but insufficient. Could you move cativty icon on same line than user for outing ?

**Comment by stef74** [comment]
if is simple align author on right if not push as this need to test different case and resolution

**Comment by ginold** [comment]
It looks ok on different resolutions:

**large screen**

screenshot from 2016-12-13 14-29-42


**actual mobile**

screenshot from 2016-12-13 14-30-47


but i think we should also change to 

screenshot from 2016-12-13 14-33-49

**Comment by stef74** [comment]
:+1:  could you push on demo when it's merged ... so other user can test.

**Comment by asaunier** [comment]
This PR must be reviewed before merging :)
@ginold is it ready for review?
If yes I will have a look.

**Comment by ginold** [comment]
Yes it's ready. It brings the changes  I listed above + outing card style like on the 1st and last screenshot of my previous comment.

**Comment by asaunier** [comment]
The code is OK for me.

I have tested the branch in my instance/browser:
* for doctypes with no geom (ie. no map in the advanced search), the cards are too wide IMO (ditto for areas):
sans titre
* in document detail view pages, since there is no map, the routes and WP cards are wider too (perhaps too wide?). For instance for WP "La Meije":
sans titre

* when there is a map, the card width is good (see screenshots above) but perhaps the threshold to the single column layout is a bit too small:
sans titre
* image cards are also wider and we only have 2 columns as for the other doctype. OK for me (what about portrait images?) but one has to be aware of this change too. See the prod for the current size.
sans titre

**Comment by ginold** [comment]
so maybe:
+ waypoints cards could have +1 more card per row ?
+ lists with no maps could have +1 more card per row?
+ will make the treshold for 1 col bigger (is 800px now) ?

**Comment by asaunier** [comment]
Makes sense to me, yes.

**Comment by asaunier** [comment]
> * waypoints cards could have +1 more card per row ?
> * lists with no maps could have +1 more card per row?

Just to make sure:
* if I have a 10000px wide screen, how many columns will I see? 2 (3 for no-map content) ? Or as many columns as it fits in the available width?
* related to https://github.com/c2corg/v6_ui/issues/1187 => when hidding the map, will it increase the number of columns or only the width of cards?

**Comment by stef74** [comment]
Ok with your last recommendation.
Is better way is now to move in demo ... to have more deep test with many resolution (assoication can do that).

**Comment by ginold** [comment]
> Or as many columns as it fits in the available width?

I think there is no such "as many as it fits" -> we have to define the max.
I hardly see people having a 10'000px wide screen but i can add a complementary case to have 4 columns :P

As for, #1187  i would prefer to handle it in <-- that pr directly if needed, not here.

**Comment by asaunier** [comment]
What I mean is that the system must be flexible: having much wider cards because the screen is larger or the map is hidden does not bring much gain. The idea is to be able to see more results (ie. more rows, more columns) when there are more space available.

**Comment by stef74** [comment]
a maths formula can help to dertermine how many colum is needed ... nb_colum = with_screen modulo ( optimal_width_of_card)
The optimal_width depend of doc type

**Comment by ginold** [comment]
the width is always a % - > 33% = 3 cards per row etc. I will define for up to 4 cards per row. I think it's impossible to have such logic in CSS as you suggest, maybe could be in JS.

**Comment by asaunier** [comment]
@ginold let me recap:
* for outings and routes we need wider cards: generally displayed in 2 cols when the map is shown (1 if the screen is a bit too narrow)
* if there is enough space (wider screen, mo map or hidden map): 3 cols, maybe 4.
* for other document types: since the cards have less content (?), 3 cols by default is OK, but of course we should be also able to see more cols (4 or 5?) when the screen is wide or when the map is hidden.
* for images? No clue if it's better to have wider cards or to keep the current width. What do you think?

Since it is important that at least a first version go to prod soon, I would recommend to use a simple CSS approach first and to use a more flexible JS approach later if needed.

Sounds good to you?

**Comment by ginold** [comment]
that's what i've done :+1: 

There are up to 4 cards per row on super large screens (+2100px) for all doctypes and +1 more card per row than the default - for lists that have no map (articles, areas...) and for waypoints. 
Should also work for associated documents on editing and view pages.

**Comment by asaunier** [comment]
@ginold I have tested with FF and Chrome on my laptop. As far as I can see, it looks good to me, thanks!

Please merge.

**Pull request merged**
