### PR TITLE
Add tool to load prefs in advanced search

### PR DESCRIPTION
**Pull request by asaunier**
Related to https://github.com/c2corg/v6_ui/issues/1342

Still some testing and fixes to do:
* [x] make sure the map is recentered on areas when loading areas prefs
* [x] make sure the activities selector is updated and consistent with the loaded prefs
* [x] when filters are cancelled (removing area prefs), make sure the map extent is reset, or at least consistent with the returned results

As for now I have not implemented any storage of the preferences as considered in https://github.com/c2corg/v6_ui/issues/1342#issuecomment-280308466 => prefs are loaded on demand when pushing the "apply my prefs" buttons, in my instance the delay is acceptable. Don't know yet if it could be OK in demo/prod as well.

capture du 2017-02-22 18-20-16
capture du 2017-02-22 18-20-42

### CODE REVIEW

**Comment by asaunier** [comment]
This PR is ready to be reviewed.

To summarize the changes:
* I have removed ``angular-debounce`` since a debouncing tool is already available in ngeo (used in most part of the code). I have then replaced ``angular-debounce`` by ``ngeo.Debounce``.
* A ``loadPreferences`` directive has been created. It is used as an attribute of whatever button (works a bit like the existing ``protected-url-btn`` directive https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/protectedurlbtn.js)
* The directive can either be used to open a new page if an additional directive attribute is provided (eg. ``app-load-preferences-url="/outings"``) or to update the fragment params (eg. ``#act=skitouring&a=12345,12346``) of the current page (used in the advanced search pages).
* Prefs are retrieved from the API the first time the button is clicked, but the prefs are not saved between pages (I think the delay is acceptable and it saves some complexity - to be confirmed).
* Depending on the document type, ``act`` (activities) and/or ``a`` (areas) params are applied.
* When area prefs are loaded the map is recentered in the extent of those areas.
* When clicking the "clear filters" button, area prefs are removed but the map extent remains unchanged.
* To be able to recenter on the area prefs, I had to skip the checkboxes panels debouncing (if you click several checkboxes in a row, the API request is made only after a slight delay, not after every single click) because I needed to had a param to the ``searchFilterChange`` event (which seemed not possible with the debounce). Perhaps it was acceptable as is. But I have however added a ``checkboxes`` buffer that is synchronised with the filters through a debounce tool to recreate the former behaviour.

Screenshots above are still valid.

**Comment by arnaud-morvan** [comment]
Unwanted behavior with activities checkboxes.
In /outings page, load my preferences, remove the filters, open activities dropdown and check one, "preferred activities" checboxes state change in background.

**Comment by arnaud-morvan** [comment]
After the preceding workflow, re-check exactly the prefered activities. The result count is not the same because of the filter on the prefered regions has been removes. The prefered regions filter is not materialized on the page, and common user do not take care of the url. This is not obvious.

**Comment by arnaud-morvan** [comment]
IMHO we should display something for the prefered areas filter in the seach form.

**Comment by arnaud-morvan** [comment]
A "Prefered areas" check box or "Areas" dropdown.

**Comment by arnaud-morvan** [comment]
Not sure the new button "See outins according to my preferences" in activity feed is at the right place. It takes a lot of place (with corresponding card / margins) for such button. May be possible move it inside the same card as "Add an outing".

**Comment by asaunier** [comment]
> IMHO we should display something for the prefered areas filter in the seach form.
> A "Prefered areas" check box or "Areas" dropdown.

This is out of scope and would require much more work.

There are 679 available areas of 3 different types: https://www.camptocamp.org/areas
Using a simple list of checkboxes or a dropdown is not possible.
The topic of an area selector has already been discussed concerning the selection of areas in the preferences page. See https://github.com/c2corg/v6_ui/issues/598 
As for now a simplified selector based upon the search tool has been implemented.

There are discussions about adding an area filter section in the advanced search page but:
* is it really needed? It's already possible to do most of the geographical filtering using the map.
* we don't really know how to render this area selection tools. It's not that simple.
* applying prefs with this PR already does most of the job, it's better to split tasks to avoid spending weeks on a PR.

I really prefer not dealing with an area selector in this PR!

> Not sure the new button "See outins according to my preferences" in activity feed is at the right place. It takes a lot of place (with corresponding card / margins) for such button. May be possible move it inside the same card as "Add an outing".

Maybe you're right. I can try moving the button to the same card than the "add an outing" button.

**Comment by arnaud-morvan** [comment]
Ok but it is really not obvious when the checkbox "Limit to visible bbox" is checked that the prefered areas are used instead. Maybe two radio buttons with new option "Limit to prefered areas".

**Comment by arnaud-morvan** [comment]
Sorry the two apply the same time so it's an "and", not radio buttons.

**Comment by asaunier** [comment]
> Ok but it is really not obvious when the checkbox "Limit to visible bbox" is checked that the prefered areas are used instead. Maybe two radio buttons with new option "Limit to prefered areas".

That sounds a bit complicated. Both in the interface (having too many inputs makes it harder to use) and in the code which is already not simple at all.

We have too much complexity in this projet. I prefer to keep things as simple as possible.

Clicking the "load my prefs" button is only a shortcut that "checks" activities and areas (perhaps langs in the future) for you depending on your prefs. But then you can change the activities (not the areas but perhaps later). So it's not very relevant to have inputs mentioning "preferd areas".
In addition having a "Limit to prefered areas" would be a duplicate of the "load my prefs" button which also limit to the prefered areas.

**Comment by asaunier** [comment]
> In /outings page, load my preferences, remove the filters, open activities dropdown and check one, "preferred activities" checboxes state change in background.

Indeed. Thanks for catching this!

**Comment by arnaud-morvan** [comment]
According that It seems really difficult to materialize the prefered areas filter in the UI (value is a list of areas, not a boolean). After you fix the clear filter behavior, it is ok for me to merge.

**Comment by asaunier** [comment]
I have updated the PR to fix the error reported by @arnaud-morvan when clearing filters.

Concerning the position of the button in the home feed:

> May be possible move it inside the same card as "Add an outing".

this definitely makes sense! By the way adding a "See outings" button instead of "See outings according to my preferences" when not authenticated would make sense too (perhaps the "Outings" entry could be removed from the menu then?).

Unfortunately I have not been able to change the styles and have the buttons rendered nicely in the same card!

Here are the additional changes I did in the feed partial https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/partials/feed.html
```
-  <article class="feed-list-item" protected-url-btn url="/outings/add" ng-if="!feedCtrl.userId">
+  <article class="feed-list-item" ng-if="!feedCtrl.userId">
     <div class="timeline-bullet icon-outings" uib-tooltip="{{'outing'| translate}}" tooltip-placement="left"></div>
     <div class="list-item vertical-align">
-      <button class="orange-btn btn" translate>add an outing</button>
+      <button class="orange-btn btn" protected-url-btn url="/outings/add" translate>add an outing</button>
+      <button class="green-btn btn" ng-if="userCtrl.auth.isAuthenticated()"
+              app-loading app-load-preferences="outings" app-load-preferences-url="/outings"
+              translate>See outings according to my preferences</button>
+      <a href="/outings" ng-if="!userCtrl.auth.isAuthenticated()">
+        <button class="green-btn btn" translate>See outings</button>
+      </a>
     </div>
   </article>
 
@@ -29,14 +35,6 @@
     </div>
   </article>
 
-  <article class="feed-list-item" ng-if="userCtrl.auth.isAuthenticated() && !feedCtrl.userId">
-    <div class="timeline-bullet icon-outings" uib-tooltip="{{'outing'| translate}}" tooltip-placement="left"></div>
-    <div class="list-item vertical-align">
-      <button class="green-btn btn" app-loading app-load-preferences="outings" app-load-preferences-url="/outings"
-              translate>See outings according to my preferences</button>
-    </div>
-  </article>
-
```
which more or less results in:

capture du 2017-03-02 17-02-14

capture du 2017-03-02 17-02-48

In addition the layout must be adapted when using a mobile screen.

I guess that on a mobile screen both buttons should take the full width of the card and be stacked above each other.
On wider screens we could have 2 side-by-side buttons (as the "Topoguide" and "Forum" buttons when not authenticated) with same width.

But I don't feel skilled enough to do so...

**Comment by arnaud-morvan** [comment]
I do not find annoying to have the buttons stacked even on wide screen.
Note that having buttons with text as long as "See outings according to my preferences" is not usual and seems little weird.

**Comment by asaunier** [comment]
> I do not find annoying to have the buttons stacked even on wide screen.

Shame on me but I am struggling to do it as well :P There are a bunch of styles on those buttons...

> Note that having buttons with text as long as "See outings according to my preferences" is not usual and seems little weird.

I understand but what text could we use instead?
It's probably useful to make people know that the button opens the outings page WITH the prefs, especially if the "Outings" entry is kept in the menu. Else people might not understand what's the use of this button?

Or perhaps we could:
* remove the "Outings" entry in the sidemenu
* have this button named "Last outings" both for authenticated users (with prefs) and for guests (no pref in that case).
?

**Comment by asaunier** [comment]
I have updated the PR to group buttons "Add an outing" and "See outings" or "See outings according to my preferences" in the same card:

capture d ecran 2017-03-03 a 17 43 07

capture d ecran 2017-03-03 a 17 43 44

When the screen gets narrower:

capture d ecran 2017-03-03 a 17 44 01
capture d ecran 2017-03-03 a 17 44 13
capture d ecran 2017-03-03 a 17 44 24

Always having the buttons the same height would make sense (see the last screenshot, for a mobilephone screen). Don't know yet how to do it.

**Comment by asaunier** [comment]
Any comment/review about this PR?
Is it OK for merging?

**Comment by arnaud-morvan** [comment]
For me it's OK, it seems that it's the better thing we can do now.

**Comment by asaunier** [comment]
@arnaud-morvan Thanks for reviewing!

**Pull request merged**
