### PR TITLE
Activity feed: no additional horizontal margin around images

### PR DESCRIPTION
**Pull request by brunobesson**
Before:
snapshot5

After:
snapshot6

### CODE REVIEW

**Comment by asaunier** [comment]
👍

**Comment by brunobesson** [comment]
@asaunier @ginold OK to merge then? This was a really simple fix. But maybe it could clash with ongoing work on activity feed and cards?

**Comment by asaunier** [comment]
OK for me. Since it impacts some @ginold 's work, I prefer to leave him the last word :)

**Comment by ginold** [comment]
ok, seems good to me :ok:

**Pull request merged**
