### PR TITLE
only markdown

### PR DESCRIPTION
**Pull request by cbeauchesne**
For testing

### CODE REVIEW

**Comment by cbeauchesne** [comment]
ps : perfs tests : 

* markdown (iso prod) : 0,012s/sample.md
* bleach : 0,006s/sample.md

**Comment by asaunier** [comment]
@cbeauchesne Good work!

Honestly I have not studied every single line of your changes and trust you :)
I have just updated the demo with the most recent docker image of your branch.
@c2corg/developers Could you check that everything looks as expected on the demo? Thanks!

A few advices:
* try to reduce as much as possible the number of commits, you can squash/group commits using the tip explained at https://github.com/c2corg/v6_ui/wiki/Git-Cookbook#managing-commits Of course if some changes are really distinct, it's OK to have dedicated commits.
* try to use more explicit commit messages. It should be possible to figure out what your commit do without having to open a linked issue etc. Especially when reviewing or looking at the commit logs: https://github.com/c2corg/v6_ui/commits/master

**Comment by cbeauchesne** [comment]
@mfournier I'd need for this change a special thing : there is a lot of tag to migrate on DB, and I need to recurrently run a big set of DB request. For the moment, I abuse of Alex kindness, but it's limited, as I've some request with bug, and a lot of others that I must run a lot of time.

The question is : would it be possible to get a daily dump of prod DB on tables : route, waypoint, book, article, area, and image?

With taht, I will be able to do this migration efficiently.

Thank you for your help!

**Comment by cbeauchesne** [comment]
I pay attnetion to use --amend, but I must miss something... :(

**Comment by cbeauchesne** [comment]
Ok, I'm ready for merging.

But before getting in prod, there is two mandatory things : 

* a demo server with an API with pretty recent DB (actual API data are far too old) for testing.
* and a DB dump, because I need to prepare the bot migration scripts.

I can merge now, but if we can't have this two things on time, it's better to wait IMO.

**Comment by cbeauchesne** [comment]
J'arrive à rien...

**Pull request closed without merging**
