### PR TITLE
User profile icon

### PR DESCRIPTION
**Pull request by ginold**
related to #769
related to #390

As @asaunier  suggested, it's a good idea to have a separate profile.svg icon, following what has been done for other document types.

I extracted the bootstrap's glyphicon user icon: 
screenshot from 2016-10-31 17-43-51

It's better than the other we have because it has no background and can be colored entirely with no empty spaces inside itself. 

The question is: are we going to use this icon for the user profile only? should we replace the other user-icon completely (used in outing-cards for exemple) ?

### CODE REVIEW

**Comment by asaunier** [comment]
> I extracted the bootstrap's glyphicon user icon:

The background circle seems a bit too small compared to the user icon (or the latter is too big?), doesn't it? We have to be consistent with the sizes of other map icons.

> The question is: are we going to use this icon for the user profile only? should we replace the other user-icon completely (used in outing-cards for exemple) ?

That would be consistent to have the same icon everywhere.
On the other hand, the current icon is not that different and perhaps it helps figure out the card with such icons are not "profile" cards but "outing" cards?

**Comment by ginold** [comment]
Yes, I can make it fit into the circle.

The advantage of this change is that it is very simple: just added a new svg and that's it, no need for regenerating the fonts and replacing all the icons.

**Comment by asaunier** [comment]
> The advantage of this change is that it is very simple:

What change?

**Comment by ginold** [comment]
> What change?

 "just added a new svg and that's it, no need for regenerating the fonts and replacing all the icons"

**Comment by asaunier** [comment]
OK, go for it.

**Comment by ginold** [comment]
updated - the user-profile icon is smaller and fit's into the circle. And I don't know what i was talking about regenerating the icons - this one is already available with glyphicon-user :p 

I will merge if no objections.

**Comment by asaunier** [comment]
I had a quick look, seems cool, thanks. Please merge.

**Pull request merged**
