### PR TITLE
Add sitemap for SEO

### PR DESCRIPTION
**Pull request by tsauerwein**
A [sitemap index](http://www.sitemaps.org/protocol.html#index) is now available at `/sitemap.xml`. This file should be linked in the robots file, see https://github.com/c2corg/v6_ui/issues/639.

Closes https://github.com/c2corg/v6_ui/issues/343
Requires https://github.com/c2corg/v6_api/pull/470

### CODE REVIEW

**Comment by asaunier** [comment]
> This file should be linked in the robots file

What about doing it in the PR?
http://robots-txt.com/ressources/robots-txt-sitemap-xml/
This way it would be ready for going live (even if it is temporarly commented out in ``robots.txt``).

Since the PR brings many changes (for instance refactoring of the API calls, caching, etc.), should we wait that the beta demo is out before merging it?

**Comment by asaunier** [comment]
Does the sitemap service supports HTTPS? I mean are the listed URLs using the https protocol?

**Comment by tsauerwein** [comment]
> Does the sitemap service supports HTTPS? I mean are the listed URLs using the https protocol?

The urls are generated with `route_url`. But we will have to test if this works correctly.

**Comment by asaunier** [comment]
Please merge if no other change is planned at short term.
I guess it's better that those changes are intensively tested with the beta instead of waiting for the golive...

**Comment by stef74** [comment]
Please inform when is avilable on demo ... i have to use it for crawling the website and identify broken link.

**Comment by asaunier** [comment]
> i have to use it for crawling the website and identify broken link.

What do you mean?
Crawling with what tool?

Please note that currently indexing is disabled in the demo:
* meta "robots" = "noindex,nofollow"
* robots.txt: "Disallow" https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/robots.txt

**Comment by stef74** [comment]
I have different tool ... wget in "spider" mode ... also this one
https://github.com/stevenvachon/broken-link-checker ... and many gui tools
but often limited in number of crawling
robot txt is not blocking (it's an option to use it or not).

The goal is to identify how many link are broken ... and define action to
fix it (probably manual fix in many case).


2016-11-07 11:04 GMT+01:00 Alex Saunier <notifications@github.com>:

**Pull request merged**
