### PR TITLE
Update angular and angular-gettext

### PR DESCRIPTION
**Pull request by gberaudo**

### CODE REVIEW

**Comment by gberaudo** [comment]
Related to #37.

**Comment by gberaudo** [comment]
The update of angular creates a regression with selects translation not updated anymore.
With @asaunier, language select has been `fixed` by removing one time binding.

**Comment by asaunier** [comment]
If no other features is broken by this update (still possible to create a WP?), I think it's OK to merge the PR.

I have just created an issue about the i18n problem:
https://github.com/c2corg/v6_ui/issues/40

**Comment by asaunier** [comment]
I have just rebased the PR and fixed a conflict in the Makefile.
Tests pass (still waiting for Travis) and the UI still works as expected except that the dropdown lists in the editing forms are no longer translated (already reported in issue #40 ).

I suggest that we merge the PR since we won't stick to Angular 1.3 and need a recent version.
@gberaudo @tsauerwein OK for merging?

**Comment by gberaudo** [comment]
+1

**Pull request merged**
