### PR TITLE
[WIP] Add possibility to revert to an archived document version

### PR DESCRIPTION
**Pull request by asaunier**
Related to https://github.com/c2corg/v6_ui/issues/1068

### CODE REVIEW

**Comment by tsauerwein** [comment]
Something to test: If a document has associations, check that these associations still exist after the revert.

**Comment by asaunier** [comment]
Indeed, that's something I needed to manage:
* hide association tools when editing an archive version
* remove ``associations`` from the posted data

What happens if there is no ``associations`` attribute in the posted data? API crashes? No change to ``associations``? All associations are removed?

**Comment by tsauerwein** [comment]
> What happens if there is no associations attribute in the posted data? API crashes? No change to associations? All associations are removed?

The associations should not be changed.

**Comment by asaunier** [comment]
Remaining tasks:
* [ ] add view/route for xreports
* [ ] check user permissions before displaying the "Restore" button in the archived versions views: auth users for collaborative docs / associated users or moderators for personal docs
* [ ] ignore associations (don't show/send them + ) when editing an archived version (including for enabling the save button when associated WP etc. are mandatory)

**Comment by asaunier** [comment]
> check user permissions before displaying the "Restore" button in the archived versions views: auth users for collaborative docs / associated users or moderators for personal docs

The first versions of this PR only showed the revert button to moderators. Commit 1401f96 uses function ``userCtrl.hasEditRights()`` which is already used to decide if the editing button should be shown in the standard view pages. Unfortunately some data such as assocations (including associated users) or creator user_id are not provided for archives. As a result the editing right permissions check does not work for personal documents (OK for collaborative docs). On the other hand since personal documents are editable only by their authors or associated users, they are much less likely to be vandalized. Moderators still have access to the revert function for such documents.

**Comment by asaunier** [comment]
Another "problem": the "revert" button is not shown (except for moderators) for protected documents... except that the "protected" attribute is the one that comes with the edited archived version!

Which means that if the document was not protected at the time of the archive, the "revert" button is shown even though the document is currently protected. On the other hand, if the document is no longer protected but was protected at the time of the archive version, the "revert" button is not shown (except for moderators).

Please note though that the API actually does a "protected" status check (based on the last version) check and will not accept a change of a protected document anyway. So it's only a UI problem.

There is no simple solution because the updated ``protected`` attribute is not available when viewing an archive. This attribute should be added by the API in the metadata provided along with the current archive document data:
https://github.com/c2corg/v6_api/blob/53ac2dc5c460fe33bcf3336b4b023cc5a451f405/c2corg_api/views/document_version.py#L74-L79
but since it is not critical and quite unlikely, perhaps we could live with this approximation.

**Comment by asaunier** [comment]
Replaced by https://github.com/c2corg/v6_ui/pull/1669

**Pull request closed without merging**
