### PR TITLE
Use multiple select for route activities

### PR DESCRIPTION
**Pull request by gberaudo**

### CODE REVIEW

**Comment by gberaudo** [comment]
Closes: https://github.com/c2corg/v6_ui/issues/41

**Comment by asaunier** [comment]
Thanks, that should actually solve the linked issue.

We can merge as is but I would prefer that we use checkboxes instead of "multiple" selects because it's a known UX problem in v5 that many people don't know that it's possible to select several options by pressing the Ctrl key and that it's also possible to remove a selected option this way. In v5, we have added a "blank" option at the beginning of such selects so that users may also set no option at all. But that sucks. Checkboxes are a better way to do this (but that's most likely a bit more complicated to handle in an angular model).

**Comment by asaunier** [comment]
In the meantime :+1: for merging this PR.

**Comment by gberaudo** [comment]
Thanks for the review @asaunier.
For now I will simply merge this fix and we can improve later as you suggested.
See issue https://github.com/c2corg/v6_ui/issues/49.

**Pull request merged**
