### PR TITLE
Angular 1.5

### PR DESCRIPTION
**Pull request by gberaudo**

### CODE REVIEW

**Comment by gberaudo** [comment]
It seems to work out of the box. I am preparing a demo.

**Comment by asaunier** [comment]
The translations (including dropdowns in editing forms) still work as well?

**Comment by gberaudo** [comment]
See http://c2corgv6-demo.gis.internal:6556/

**Comment by asaunier** [comment]
Seems OK indeed. Thanks!

**Comment by gberaudo** [comment]
Thanks for the review.

**Pull request merged**
