### PR TITLE
Add Python 3.5 note in the requirements doc

### PR DESCRIPTION
**Pull request by asaunier**
Fixes https://github.com/c2corg/v6_ui/issues/437

### CODE REVIEW

**Comment by asaunier** [comment]
Any objection?

**Comment by tsauerwein** [comment]
:+1:

**Comment by asaunier** [comment]
Thanks @tsauerwein :)

**Comment by mfournier** [comment]
@asaunier, @tsauerwein, would it be an idea to test both python versions in travis-ci, the same way nodejs 4 and 6 are currently tested in parallel ?

**Comment by asaunier** [comment]
No clue.
As for now we only use python 3.4. Is it really useful to test with 3.5 if anyway we have no infrastructure to make the required changes for 3.5?

**Pull request merged**
