### PR TITLE
fix bad rendering in mobile

### PR DESCRIPTION
**Pull request by stef74**
#1623

### CODE REVIEW

**Comment by stef74** [comment]
capture d ecran 2017-05-10 a 20 38 36

**Comment by asaunier** [comment]
The rendering is indeed OK in a narrow screen but in a wider screen the cards are also displayed in a single column (OK for intermediate screen widths). For instance on my laptop:

capture d ecran 2017-05-10 a 21 40 21

**Comment by stef74** [comment]
Strange on my test is distribute on many column. I have look tomorrow evening. The principe of this change is define a 'base' of card at 100px and offer possibility to enlarge.

**Comment by stef74** [comment]
I have do some sheet, I close an recreate

**Comment by asaunier** [comment]
Don't forget to delete the branch when closing an unmerged PR.
Please note that it was not necessary to create another branch, you could have changed the commits and "push force" the branch with the new commits. See https://github.com/c2corg/v6_ui/wiki/Git-Cookbook#managing-commits

**Pull request closed without merging**
