### PR TITLE
Add compatibility with node 6 / npm 3

### PR DESCRIPTION
**Pull request by gberaudo**
- directly depend on closure-util;
- add Travis tests using node 6 (current) and node 4 (LTS).

### CODE REVIEW

**Comment by asaunier** [comment]
OK for me. Just curious why you made this change?

**Comment by gberaudo** [comment]
Last week, @ginold updated its version of node/npm to latest stable and was blocked because it would not compile. This is somehow related to https://github.com/c2corg/v6_ui/issues/74 (same error message as Adam).

**Comment by asaunier** [comment]
Looks good to me.

**Comment by gberaudo** [comment]
Thanks for the review @asaunier.

**Pull request merged**
