### PR TITLE
Form feedback rework

### PR DESCRIPTION
**Pull request by brunobesson**
* Ensure feedback is displayed in login and signin forms
* Rework feedback in topoguide forms: use consistent coloring
* Ensure all feedbacks have enough place to be displayed
* Re-tested every field, added some more constraints, corrected some typos

See #1525 and #1526

### CODE REVIEW

**Comment by brunobesson** [comment]
Good luck to those that are willing to review :rofl:

**Comment by asaunier** [comment]
> Good luck to those that are willing to review 

That's motivating :P 
I'll test and review your PR but I'am afraid I cannot do it before sunday evening or the beginning of next week.

**Comment by brunobesson** [comment]
I'm only saying this because I have changed a lot of lines, so willing to check each and every typo is cumbersome :sweat: 
As for testing, you could focus on 2 things:
* the signin / login / ... forms show feedback
* try some fields for guidebook documents that are required or have a constraint (number, URL, ...) and check the feedback appears.

And then have faith in me :innocent: 
I personally tried to check each and every field, but I might quite easily have missed something.

**Comment by asaunier** [comment]
The code changes look OK to me.
I have also tested almost all forms with validations (sign in/up, forgotten password, editing forms of all doctypes). The result is very nice and handy!

A very minor point though:
* attribute ``elevation`` of the xreport editing form is not mandatory (and the validation does not complain if it is missing). This is correct. But then the asterisk on the attribute title should be removed.

**Comment by brunobesson** [comment]
>very minor point though

That's a nice catch! You did your review the right way :+1: 
I updated my commit to remove the mandatory decoration, will merge once CI is OK.
(Big) thanks for this cumbersome review

**Pull request merged**
