### PR TITLE
Remove BBCode parser, and add Bleach sanitizer

### PR DESCRIPTION
**Pull request by cbeauchesne**

### CODE REVIEW

**Comment by cbeauchesne** [comment]
@asaunier, my first PR without a mess from hell? 😉

**Comment by cbeauchesne** [comment]
yet another noob question : merge commit, or rebase and merge?

**Comment by brunobesson** [comment]
You merge only. Rebase and merge will do similar to squash, but leaving the whole list of commits.

So you merge the PR. But first, you ensure to have a nice graph by rebasing your branch with master:

```
git checkout master
git pull
git checkout onlymarkdown2
git rebase master
git push --force
```
And then you can merge through github's interface.

**Comment by cbeauchesne** [comment]
ok, I will do it tonight.

**Comment by asaunier** [comment]
> So you merge the PR. But first, you ensure to have a nice graph by rebasing your branch with master:

True. But not that required for a recent PR with no reported conflict.

**Comment by brunobesson** [comment]
>But not that required for a recent PR with no reported conflict.

Even in this case, it is better to do so to produce a more readable network graph IMHO.

**Comment by asaunier** [comment]
@cbeauchesne Do we still need the bbcode python module? It is still required in https://github.com/c2corg/v6_ui/blob/master/requirements.txt#L11 => should we remove it?

**Comment by cbeauchesne** [comment]
No, I've forgotten to remove it, sorry.

**Pull request merged**
