### PR TITLE
Print button

### PR DESCRIPTION
**Pull request by brunobesson**
* Adds print button to "plus" menu
* Adds icons for dropdown actions
* Changes "plus" menu icon

movement5

### CODE REVIEW

**Comment by brunobesson** [comment]
See #1581

**Comment by brunobesson** [comment]
Or maybe, assuming there is need for this button only on desktops and tablets, we could add the print button as a top level button between comments and plus, hidden on mobile.
What do you think?

**Comment by asaunier** [comment]
> What do you think?

I don't have a strong opinion. I feel a bit amazed that we need to add such a print button: people don't even know the basic features of a browser/website? no surprise then that they sometimes have a hard time with c2corg which offers a lot of advanced features.
I am a bit concerned that adding another button will make the other buttons harder to figure out (the fewer buttons, the better?).

**Comment by brunobesson** [comment]
Let's stick to this proposal then, we can easily switch to another solution if needed. @desnoes @mgerbaux do you have a non-dev point of view about this subject?

**Comment by mgerbaux** [comment]
If I understand Alex's point of view, I think that adding a dedicated printing button make people more confident than using the default browser 's one : they would think that lead to a good printing quality rather than a screen print, many of them do not know very well the behavior of their browser.

**Comment by brunobesson** [comment]
>I think that adding a dedicated printing button make people more confident

OK, that's why I added this button in the plus button dropdown. The question being: is that enough, or do we need a "top leve" print button?

**Comment by mgerbaux** [comment]
I think we can leave it in the "plus" sub-menu

**Comment by desnoes** [comment]
> I think we can leave it in the "plus" sub-menu

I agree with this solution

**Pull request merged**
