### PR TITLE
Colored icons for outings with condition ratings.

### PR DESCRIPTION
**Pull request by asaunier**
* show a colored point with tooltip in cards depending on the condition rating, see https://github.com/c2corg/v6_ui/issues/1558
* use colored icons on the map depending on the condition rating, see https://github.com/c2corg/v6_ui/issues/1557

capture du 2017-03-21 16-18-38

The positioning of the condition rating indicator in the cards is poor because it will anyway be changed in other PR, like https://github.com/c2corg/v6_ui/pull/1449

Colors are not exactly the same than in the issues:
> Excellent: blue 100%
Good: blue 50%
Average : yellow
poor: red 50%
Awful: red 100%

because I could not use alpha/opacity settings (is it the meaning of 50%?) on the outings SVG used in the map.
Here are the colors that have been used:
```
Excellent: #0000FF (blue) => unchanged
Good: #00FFFF (cyan) => changed
Average : #FFFF00 (yellow) => unchanged
poor: #FF00FF (purple) => changed
Awful: #FF0000 (red) => unchanged
```

@desnoes Could you please confirm the colors are OK or give me more precisions about the colors to use (hexadecimal codes as above)?

### CODE REVIEW

**Comment by asaunier** [comment]
Colors have been updated according to @desnoes ' proposal:

> Excellent: #008000 (green)
Good: #9ACD32 (light green) 
Average : #FFFF00 (yellow)
poor: #FF0000(red)
Awful: #8B0000 (dark red)

capture du 2017-03-22 14-32-37

**Comment by asaunier** [comment]
@desnoes Is it OK with the new colors?

**Comment by desnoes** [comment]
@asaunier: yes it's ok.

**Comment by asaunier** [comment]
@desnoes Thanks!
@arnaud-morvan Any objection against merging the PR?

**Comment by arnaud-morvan** [comment]
No objection, feel free to merge

**Comment by asaunier** [comment]
@arnaud-morvan Thanks!

**Pull request merged**
