### PR TITLE
Fix OL3 and Ngeo versions

### PR DESCRIPTION
**Pull request by gberaudo**
This commit fixes dependency versions, which makes sure we are running
the application in a tested environment.

### CODE REVIEW

**Comment by gberaudo** [comment]
Was getting unexpected errors from ngeo master.

```
npm install
npm WARN package.json c2corg_ui@0.0.1 No repository field.
touch .build/node_modules.timestamp
mkdir -p c2corg_ui/static/build/
./node_modules/openlayers/node_modules/.bin/closure-util build build.json c2corg_ui/static/build/build.js
info closure-util Reading build config
info closure-util Getting Closure dependencies
info closure-util Compiling 402 sources
ERR! compile /home/gberaudo/dev/c2cv6ui/node_modules/ngeo/src/directives/map.js:16: ERROR - Parse error. illegal use of unknown JSDoc tag "ngdoc"; ignoring it
ERR! compile  * @ngdoc directive
ERR! compile    ^
ERR! compile
ERR! compile
ERR! compile /home/gberaudo/dev/c2cv6ui/node_modules/ngeo/src/directives/map.js:17: ERROR - Parse error. illegal use of unknown JSDoc tag "ngname"; ignoring it
ERR! compile  * @ngname ngeoMap
ERR! compile    ^
ERR! compile
ERR! compile /home/gberaudo/dev/c2cv6ui/node_modules/ngeo/src/services/getbrowserlanguage.js:22: ERROR - Parse error. illegal use of unknown JSDoc tag "ngdoc"; ignoring it
ERR! compile  * @ngdoc service
ERR! compile    ^
ERR! compile
ERR! compile /home/gberaudo/dev/c2cv6ui/node_modules/ngeo/src/services/getbrowserlanguage.js:23: ERROR - Parse error. illegal use of unknown JSDoc tag "ngname"; ignoring it
ERR! compile  * @ngname ngeoGetBrowserLanguage
ERR! compile    ^
ERR! compile
ERR! compile
ERR! compile 4 error(s),
ERR! compile 0 warning(s)
ERR! compile
ERR! closure-util Process exited with non-zero status, see log for more detail: 4
```

**Comment by tsauerwein** [comment]
:+1:

**Comment by asaunier** [comment]
OK

**Comment by gberaudo** [comment]
Thanks for the review.

**Pull request merged**
