### PR TITLE
Add styles for ng-cloak to the base.html to apply them correctly

### PR DESCRIPTION
**Pull request by dkocich**
I was wondering what is the problem with loading and showing some angular variables like `{{resCounter}} {{filtersCtrl...}}`, some DIVs appear and then disappear (they are visible to moderators, etc.). This should be probably hidden. We already use `Ng-cloak` ([docs](https://docs.angularjs.org/api/ng/directive/ngCloak)) in the code for that elements, but for some reason, the styles for it are not applied (they are contained inside in angular js files which are loaded after the page loads???).

I added the styles to base.html so they are loaded immediately and now pages are loading correctly (but it should be probably added somewhere else? I didn't find any angular related .less style files).

Sometimes this feature like it is now can be actually useful for debugging (it works with `?debug` URL now, but that is not available on demo for testers), so feel free to discuss / merge.

Before:
image

After:
image

### CODE REVIEW

**Comment by asaunier** [comment]
You're right, having all those temporary expression appearing at loading time is a bit ugly. If you have found a solution, that's really cool, thanks!

No idea if there is a more relevant place to put those styles than in ``base.html``. I think it's OK. @ginold OK for you?

**Comment by ginold** [comment]
I would add this part of code to helpers.less or to the main c2corg_ui.less . 

I was telling myself that those tags should be hidden by default, by I didn't realize that it was an issue - i thought it 'is the way it is'.

Other than that - :+1:

**Comment by asaunier** [comment]
> I would add this part of code to helpers.less or to the main c2corg_ui.less

Isn't the problem related to the fact that styles in CSS files are loaded too late? The temporary expressions are then displayed in the meantime.  If we add those ngCloak styles to the HTML page they are loaded faster, aren't they?

**Comment by ginold** [comment]
That's a good question, and that would make sense.
If @dkocich could do a little performance comparison with this block of code inside base.html and a less file - I would appreciate :P

**Comment by dkocich** [comment]
I tried to put it to` c2corg_ui.less` and recompile my project already in the morning. I think it did not work, but I was not sure if it is problem with the browser cache / Less minification (or it is already too late to use when it lies somewhere in the built CSS file)... When I put it to the `base.html`, it was immediately ok.

I added extra commit - tried to add ng-cloak to page main DIV (`<html ng-cloak>`) and do maybe 10 tests with the articles page (there are no map tiles loading, etc.). Every time the load time was around 2,5s instead of previous 3,5s, so the page is now faster when it don't have to restyle everything few times.

**Comment by asaunier** [comment]
I have the feeling that adding the styles in ``base.html``, as you suggested, is the best solution.

Concerning ``<html ng-cloak>``, does this mean it is useless to add ``ng-cloak`` to any other element?

**Comment by dkocich** [comment]
In docs they say:

> The directive can be applied to the <body> element, but the preferred usage is to apply multiple ngCloak directives to small portions of the page to permit progressive rendering of the browser view.

I don't know what can be a problem later (I could not find any problems now). I think that if we will keep adding ng-cloak where possible and later we will see some problem, it will be easy to just remove it from the root HTML div (delete one commit).

If I leave PR without 2nd commit - (having ng-cloak on root), there are still some things jumping around on the page (text are retranslated from initial values, icons in the sidebar are showing up, etc.). With that, we are sure that everything is covered everywhere on the page.

**Comment by asaunier** [comment]
OK, I'll test your branch this week end, I think. I let you know. Thanks anyway!

**Comment by asaunier** [comment]
I have just tested the PR (with ``<html ng-cloak>``.

Pros:
* no more ugly ``{{ foobar }}`` in any page => really cool!
* pages are rendered neatly

Cons:
* pages take a bit longer to be render, since they are only rendered when they are ready

=> For the first loaded page, the screen can remain blank a few seconds
For following pages, it's not that bad because the previous page remains displayed in the mean time (no blank page). If we had the angular-loading-bar (see https://github.com/c2corg/v6_ui/issues/593#issuecomment-258136632) would the loading bar be displayed when loading a new page. If yes, it could be acceptable (would work a bit like in github actually).

Anyway the changes look very interesting!

**Comment by gottferdom** [comment]
I totally agree with @asaunier!

**Comment by dkocich** [comment]
Does that mean I should merge @asaunier ?

**Comment by asaunier** [comment]
What about adding the angular-loading-bar to this PR?

@tsauerwein said it worked out of the box in another project, then I guess it's not a big deal to add it. And it would be a good way to test if this would solve https://github.com/c2corg/v6_ui/issues/593 and https://github.com/c2corg/v6_ui/issues/456

**Comment by tsauerwein** [comment]
> What about adding the angular-loading-bar to this PR?

I would recommend to do it in a separate PR. And like I said, the problem will be to make it play nicely with the other loading indicators.

**Comment by asaunier** [comment]
OK, than @dkocich OK for merging your PR, thanks!

**Pull request merged**
