### PR TITLE
Only authenticated users should have access to editing pages

### LINKED ISSUE #103: Make sure unauthenticated users have no access to the editing pages

### PR DESCRIPTION
**Pull request by asaunier**
Fixes #103 

* [x] Redirect unauthenticated users to auth page before giving them access to the editing pages
 * [x] View page > edit current doc
 * [x] View page > translate current doc (x ? other cultures)
 * [x] List page > add a new doc
* [x] When loading the editing page (form) => check if user is auth. If yes => nothing to do. If no:
 * [x] disable the AJAX request feeding the form
 * [x] redirect to auth page
 * [x] show alert message when user tries to save editing form while no longer authenticated
* [ ] Editing page: what if user logs out while on the editing page => form should become inactive?!

### CODE REVIEW

**Comment by asaunier** [comment]
This PR is ready for review.

Point ``Editing page: what if user logs out while on the editing page => form should become inactive?!`` is still TODO but could be treated in a separated issue/PR.

**Comment by tsauerwein** [comment]
> Point Editing page: what if user logs out while on the editing page => form should become inactive?! is still TODO but could be treated in a separated issue/PR.

When saving the form, the API will return an unauthenticated error. We could then show a message and tell the user to log in.

**Comment by asaunier** [comment]
> When saving the form, the API will return an unauthenticated error. We could then show a message and tell the user to log in.

That's already done by https://github.com/c2corg/v6_ui/commit/5bb21a857e2695dc03f22c2c12f8619db163623c
=> an auth check is done before triggering the request to the API => if false a message is shown
=> if the API is requested anyway and returns a 403, a message is shown as well

But I meant we could make it more obvious that the user is no longer logget out and then cannot push the changes unless logging in first. I admit it's an "optional" improvement, that's why I think it could be done in a separated PR.

**Comment by tsauerwein** [comment]
> But I meant we could make it more obvious that the user is no longer logget out and then cannot push the changes unless logging in first. I admit it's an "optional" improvement, that's why I think it could be done in a separated PR.

I would consider that a *nice-to-have*. I don't think this case occurs that often.

**Comment by tsauerwein** [comment]
That looks great to me! :+1:

**Comment by asaunier** [comment]
Thanks @tsauerwein for the review. I have fixed the typo.

I will merge when PR #98 is merged (I'll probably have to fix conflicts first).

**Pull request merged**
