### PR TITLE
Feed inner items styling

### PR DESCRIPTION
**Pull request by brunobesson**
* same border for images and outings/waypoints/other cards
* add margin around boxes

Before:
before
After:
after

### CODE REVIEW

**Comment by ginold** [comment]
:+1:  for border color.

I was testing with a bigger padding and margins when I was creating the cards, but I didn't like it :P but it's a question of taste - as it pleases you (and the association) !

**Comment by besson-genostar** [comment]
I propose we merge this PR for now, as it at least add consistent look&feel. We can always change the layout later.
Do you agree with merging?

**Comment by brunobesson** [comment]
I propose we merge this PR for now, as it at least add consistent look&feel. We can always change the layout later.
Do you agree with merging?

**Comment by ginold** [comment]
yes no problem. Just squash your commits into a single one or remove the 2 first.

**Pull request merged**
