### PR TITLE
remove useless '== true'

### PR DESCRIPTION
**Pull request by brunobesson**

### CODE REVIEW

**Comment by asaunier** [comment]
Thanks! Perhaps try to remove the ``ng-checked``? I have the feeling that a checkbox whose ``ng-model`` is true will already be checked (not sure).

**Comment by brunobesson** [comment]
I am more fluent with angular 2+, but your assertion seems OK to me. I'll have a look sometimes, when I find the time. I'll add the correction there if applies, before merging.

**Comment by asaunier** [comment]
By the way the doc https://docs.angularjs.org/api/ng/directive/ngChecked says
> Note that this directive should not be used together with ngModel, as this can lead to unexpected behavior.

:P

**Comment by brunobesson** [comment]
> if you have tested and make sure the behaviour is as expected.

Of course I did :wink:

**Pull request merged**
