### PR TITLE
orientation overlap

### PR DESCRIPTION
**Pull request by stef74**

### CODE REVIEW

**Comment by stef74** [comment]
capture d ecran 2017-04-25 a 12 38 11

Now orientation is only show 2 and after "..."

**Comment by stef74** [comment]
ready for review

**Comment by brunobesson** [comment]
A note aside: couldn't we imagine using SVG fonts similar to the wind rose for this? Would it be readable enough?

**Comment by asaunier** [comment]
>  couldn't we imagine using SVG fonts similar to the wind rose for this?

That looks like a good idea :)

**Pull request merged**
